### ISSUE TITLE
marko-express does not work in node v8.9.4

### ISSUE THREAD

**Issue by budden** [marko-js/marko#1001]
### Marko Version: x.x.x

```
─┬ lasso@2.11.24
│ └── marko@4.8.0  deduped
└── marko@4.8.0 
```
### Details

Tried to run marko-express according to the manual. 

### Expected Behavior

I don't know exactly. 

### Actual Behavior

Produces a stack trace :)
### Possible Fix

Wait a minute... 

<details><summary>Additional Info</summary>

### Your Environment

* Environment name and version (e.g. Chrome 39, node.js 5.4):
node v8.9.4
* Operating System and version (desktop or mobile):
```
uname -a
Linux d9 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
```
* Link to your project:
N/A

### Steps to Reproduce

1. Install debian 4.9.65 on 64-bit AMD 
2. Install node v8.9.4
3. 
```
git clone https://github.com/marko-js-samples/marko-express.git
cd marko-express
npm install
node server.js
```
BTW, it is out of sync with [Express + Marko page in docs](https://markojs.com/docs/express/)

### Stack Trace

```
/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:138
            throw createError(errorMessage, err /* cause */);
            ^

Error: Generating code for TemplateRoot node failed. Error: Error: Generating code for <lasso-page> tag failed. Error: TypeError: Cannot set property 'dirname' of null
    at module.exports (/y/marko-express/node_modules/marko/node_modules/raptor-util/createError.js:7:50)
    at CodeGenerator._invokeCodeGenerator (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:138:19)
    at CodeGenerator._generateCode (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:219:38)
    at CodeGenerator.generateCode (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:263:14)
    at Compiler.compile (/y/marko-express/node_modules/marko/src/compiler/Compiler.js:166:38)
    at _compile (/y/marko-express/node_modules/marko/src/compiler/index.js:99:33)
    at Object.compile (/y/marko-express/node_modules/marko/src/compiler/index.js:113:12)
    at compile (/y/marko-express/node_modules/marko/src/node-require/index.js:52:38)
    at Object.markoRequireExtension [as .marko] (/y/marko-express/node_modules/marko/src/node-require/index.js:120:27)
    at Module.load (module.js:556:32)
Caused by: Error: Generating code for <lasso-page> tag failed. Error: TypeError: Cannot set property 'dirname' of null
    at module.exports (/y/marko-express/node_modules/marko/node_modules/raptor-util/createError.js:7:50)
    at CodeGenerator._invokeCodeGenerator (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:138:19)
    at CodeGenerator._generateCode (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:219:38)
    at node.forEach (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:151:26)
    at ArrayContainer.forEach (/y/marko-express/node_modules/marko/src/compiler/ast/ArrayContainer.js:18:26)
    at CodeGenerator._generateCode (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:149:18)
    at CodeGenerator.generateCode (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:263:14)
    at TemplateRoot.generateCode (/y/marko-express/node_modules/marko/src/compiler/ast/TemplateRoot.js:40:29)
    at CodeGenerator._invokeCodeGenerator (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:119:29)
    at CodeGenerator._generateCode (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:219:38)
Caused by: TypeError: Cannot set property 'dirname' of null
    at /y/marko-express/node_modules/marko/src/compiler/ast/CustomTag.js:377:41
    at /y/marko-express/node_modules/marko/src/compiler/taglib-loader/Tag.js:68:22
    at module.exports (/y/marko-express/node_modules/marko/node_modules/raptor-util/forEachEntry.js:32:17)
    at Tag.forEachImportedVariable (/y/marko-express/node_modules/marko/src/compiler/taglib-loader/Tag.js:67:9)
    at CustomTag.buildInputProps (/y/marko-express/node_modules/marko/src/compiler/ast/CustomTag.js:373:20)
    at CustomTag.generateCode (/y/marko-express/node_modules/marko/src/compiler/ast/CustomTag.js:735:31)
    at CodeGenerator._invokeCodeGenerator (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:119:29)
    at CodeGenerator._generateCode (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:219:38)
    at node.forEach (/y/marko-express/node_modules/marko/src/compiler/CodeGenerator.js:151:26)
    at ArrayContainer.forEach (/y/marko-express/node_modules/marko/src/compiler/ast/ArrayContainer.js:18:26)

```
</details>

**Comment by mlrawlings** [comment]
Fixed in `marko@4.9.3` - thanks for the PR!
