### ISSUE TITLE
Marko file with the same name as an HTML tag will cause a Render error

### ISSUE THREAD

**Issue by radum** [marko-js/marko#1132]
### Details

If I have the following structure:

```
// layout.marko
<include('./components/header.marko') />
<include(input.body)/>
<include('./components/footer.marko') />
```

```
<include('./layout.marko')>
<@body>
  <main id="app">
    <header>
      Text here
    </header>
  </main>
</@body>
</include>
```

On render (via Express.js) the rendering engine will fail with this error:

```
Error: Render error. Exception: RangeError: Maximum call stack size exceeded
    at new ServerComponent (/Users/rmicu/personal/projects/webapp-boilerplate/node_modules/marko/src/components/registry.js:1:1)
    at Object.createComponent [as ___createComponent] (/Users/rmicu/personal/projects/webapp-boilerplate/node_modules/marko/src/components/registry.js:34:21)
    at Function.renderer (/Users/rmicu/personal/projects/webapp-boilerplate/node_modules/marko/src/components/renderer.js:113:34)
    at deferredRenderer (/Users/rmicu/personal/projects/webapp-boilerplate/node_modules/marko/src/runtime/helpers.js:45:26)
    at wrappedRenderer (/Users/rmicu/personal/projects/webapp-boilerplate/node_modules/marko/src/runtime/helpers.js:217:13)
    at render (/Users/rmicu/personal/projects/webapp-boilerplate/src/html/components/header.marko.js:18:3)
    at Function.renderer (/Users/rmicu/personal/projects/webapp-boilerplate/node_modules/marko/src/components/renderer.js:217:9)
    at deferredRenderer (/Users/rmicu/personal/projects/webapp-boilerplate/node_modules/marko/src/runtime/helpers.js:45:26)
    at wrappedRenderer (/Users/rmicu/personal/projects/webapp-boilerplate/node_modules/marko/src/runtime/helpers.js:217:13)
    at render (/Users/rmicu/personal/projects/webapp-boilerplate/src/html/components/header.marko.js:18:3)
    at AsyncStream.error (/Users/rmicu/personal/projects/webapp-boilerplate/node_modules/marko/src/runtime/html/AsyncStream.js:437:13)
    at Timeout._onTimeout (/Users/rmicu/personal/projects/webapp-boilerplate/node_modules/marko/src/runtime/renderable.js:17:22)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

Took me a while to realise that is because the name of the component file is `header.marko`, just like the header HTML tag I am adding in my code. Renaming the file to `_header.marko` fixes the problem obviously, but this should not break right?

I guess because `layout.marko` imports header it passes the reference to the imported file to all its descendants? Am I correct? and this is why using header deep inside will cause an error because is not used properly in a marko include way.

Not sure if this should be fixed, or at least an error with the description of the cause should actually be triggered.

### Expected Behavior

Rendering should not fail, or at least it should be more descriptive.

### Actual Behavior

Rendering fails hard hitting the stack trace limit with no indication why it might fail.

### Possible Fix

I think I get why this is a problem but at least a proper error message could be triggered.

### Your Environment

- Environment name and version: Node 10
- Operating System and version (desktop or mobile): MacOS

### Stack Trace

See my code above.

**Comment by DylanPiercey** [comment]
This was resolved, not sure when 😓
