### ISSUE TITLE
Error:Unexpected token .: ._1 after upgrade

### ISSUE THREAD

**Issue by torosm** [marko-js/marko#1230]
### Details
Error occurred after upgrade to Marko 4.14.17 from 4.14.8 (error occurred after 4.14.8 to current).

### Actual Behavior

Displayed error in the screen: See Stack Trace

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Chrome: v65, Node:v10.15.0 
- Fedora 29

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

Error: 
Unexpected token .: ._1
                     ^
    at parseExpression (/home/user/tsmis/dev/node_modules/marko/src/compiler/util/parseJavaScript.js:431:28)
    at module.exports (/home/user/tsmis/dev/node_modules/marko/src/compiler/util/parseExpression.js:4:12)
    at Builder.parseExpression (/home/user/tsmis/dev/node_modules/marko/src/compiler/Builder.js:470:22)
    at Normalizer.normalizeElement (/home/user/tsmis/dev/node_modules/marko/src/compiler/Normalizer.js:104:27)
    at Walker.exit [as _exit] (/home/user/tsmis/dev/node_modules/marko/src/compiler/Normalizer.js:73:50)
    at Walker.walk (/home/user/tsmis/dev/node_modules/marko/src/compiler/Walker.js:134:25)
    at nodes.forEach.node (/home/user/tsmis/dev/node_modules/marko/src/compiler/Walker.js:70:36)
    at ArrayContainer.forEach (/home/user/tsmis/dev/node_modules/marko/src/compiler/ast/ArrayContainer.js:18:26)
    at Walker._walkContainer (/home/user/tsmis/dev/node_modules/marko/src/compiler/Walker.js:69:15)
    at Walker.walk (/home/user/tsmis/dev/node_modules/marko/src/compiler/Walker.js:118:18)
    at HtmlElement.walk (/home/user/tsmis/dev/node_modules/marko/src/compiler/ast/HtmlElement/index.js:219:28)
    at Walker.walk (/home/user/tsmis/dev/node_modules/marko/src/compiler/Walker.js:123:22)
    at nodes.forEach.node (/home/user/tsmis/dev/node_modules/marko/src/compiler/Walker.js:70:36)
    at ArrayContainer.forEach (/home/user/tsmis/dev/node_modules/marko/src/compiler/ast/ArrayContainer.js:18:26)
    at Walker._walkContainer (/home/user/tsmis/dev/node_modules/marko/src/compiler/Walker.js:69:15)
    at Walker.walk (/home/user/tsmis/dev/node_modules/marko/src/compiler/Walker.js:118:18)
</details>

**Comment by DylanPiercey** [comment]
@torosm thanks for creating the issue. Would you be able to provide the template that is causing the issue as well?

**Comment by torosm** [comment]
Hi There,

Figured out the issue.  Error is cause by using the deprecated "include" tag.

1. Error happened when using include tag with more than one level directory path e.g ('../.../do/re/me').
2. No error if the path is in the same directory e.g ('./do').


Cheers

**Comment by DylanPiercey** [comment]
This should work with the deprecated include tag as well and is likely a regression from one of our recent migration changes. Going to reopen this issue and get a fix out soon 🙂
