### ISSUE TITLE
Error: Render error. Exception: TypeError: renderFunc is not a function

### ISSUE THREAD

**Issue by basickarl** [marko-js/marko#1241]
marko 4.1.2
Windows 10 (I get this on Ubuntu as well though).
Node 8.9

So I got this error before and you guys asked how it happened, I didn't really know so I didn't respond. It however happened now again.

So I first try and load 127.0.0.1 via my browser. The first "Error: Cannot find module" shows up in the logs. I then proceed and type the address in again in the borwser and press enter and the second log appears " Error: Render error. Exception: TypeError: renderFunc is not a function". As seen below.
```
</details>
  Error: Cannot find module 'application/client/components/d__buttonnotification-text'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
      at Function.Module._resolveFilename (C:\Users\karl\Documents\Development\langurama\node_modules\require-self-ref\src\index.js:28:35)
      at Function.Module._load (internal/modules/cjs/loader.js:507:25)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at Object.<anonymous> (C:\Users\karl\Documents\Development\langurama\application\client\utils.js:2:29)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)


  Error: Render error. Exception: TypeError: renderFunc is not a function
      at safeRender (C:\Users\karl\Documents\Development\langurama\node_modules\marko\dist\runtime\renderable.js:6:9)
      at Template.render (C:\Users\karl\Documents\Development\langurama\node_modules\marko\dist\runtime\renderable.js:132:20)
      at Readable._read (C:\Users\karl\Documents\Development\langurama\node_modules\marko\dist\runtime\html\Template.js:38:18)
      at Readable.read (_stream_readable.js:452:10)
      at resume_ (_stream_readable.js:899:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
      at AsyncStream.error (C:\Users\karl\Documents\Development\langurama\node_modules\marko\dist\runtime\html\AsyncStream.js:425:13)
      at Timeout._onTimeout (C:\Users\karl\Documents\Development\langurama\node_modules\marko\dist\runtime\renderable.js:17:22)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
```

**Comment by DylanPiercey** [comment]
I'm happy to look into this issue with an updated reproduction repo. Having said that I think likely this issue has been solved in newer versions of Marko / ecosystem plugins.
