### ISSUE TITLE
marko/hot-reload exception

### ISSUE THREAD

**Issue by cameronbraid** [marko-js/marko#1282]
### Demo

git clone https://github.com/cameronbraid/marko-browser-refresh-issue
cd marko-browser-refresh-issue
yarn
yarn server
chrome http://localhost:8001
make a change to page.marko then reload the index page

### Marko Version: x.x.x

4.15.4

### Details

After saving a .marko file and reloading the browser I get 

```
Error: Render error. Exception: TypeError: Cannot read property 'apply' of undefined
    at hotReloadProxy (/media/workspace/marko-browser-refresh-issue/node_modules/marko/src/hot-reload.js:97:31)
    at dynamicTag (/media/workspace/marko-browser-refresh-issue/node_modules/marko/src/runtime/helpers.js:200:21)
    at render (/media/workspace/marko-browser-refresh-issue/decorator.marko.js:21:3)
    at /media/workspace/marko-browser-refresh-issue/node_modules/marko/src/components/renderer.js:219:13
    at Object.renderComponent (/media/workspace/marko-browser-refresh-issue/node_modules/marko/src/components/mobx-helper.js:95:9)
    at Template.renderer (/media/workspace/marko-browser-refresh-issue/node_modules/marko/src/components/renderer.js:216:20)
    at hotReloadProxy (/media/workspace/marko-browser-refresh-issue/node_modules/marko/src/hot-reload.js:97:31)
    at safeRender (/media/workspace/marko-browser-refresh-issue/node_modules/marko/src/runtime/renderable.js:6:9)
    at Template.render (/media/workspace/marko-browser-refresh-issue/node_modules/marko/src/runtime/renderable.js:136:20)
    at Readable._read (/media/workspace/marko-browser-refresh-issue/node_modules/marko/src/runtime/html/Template.js:37:18)
    at AsyncStream.error (/media/workspace/marko-browser-refresh-issue/node_modules/marko/src/runtime/html/AsyncStream.js:441:13)
    at Timeout._onTimeout (/media/workspace/marko-browser-refresh-issue/node_modules/marko/src/runtime/renderable.js:17:22)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

### Expected Behavior

No error

**Comment by basickarl** [comment]
I'm also getting this error:
`[browser-refresh] File has been changed: application/client/components/a__landing/index.marko
[browser-refresh] Special reload: /application/client/components/a__landing/index.marko
[marko/hot-reload] File modified: /home/karl/dev/langurama/application/client/components/a__landing/index.marko
[lasso] File modified: /home/karl/dev/langurama/application/client/components/a__landing/index.marko
[lasso/browser-refresh] File modified: /home/karl/dev/langurama/application/client/components/a__landing/index.marko
[browser-refresh] Triggering refresh of client pages...
[browser-refresh] Refresh triggered
* page landing
[marko/hot-reload] Template successfully reloaded: /home/karl/dev/langurama/application/client/pages/landing/landing.marko.js

  Error: Render error. Exception: TypeError: Cannot read property 'apply' of undefined
      at hotReloadProxy (/home/karl/dev/langurama/node_modules/marko/src/hot-reload.js:97:31)
      at safeRender (/home/karl/dev/langurama/node_modules/marko/src/runtime/renderable.js:6:9)
      at Template.render (/home/karl/dev/langurama/node_modules/marko/src/runtime/renderable.js:136:20)
      at Readable._read (/home/karl/dev/langurama/node_modules/marko/src/runtime/html/Template.js:37:18)
      at Readable.read (_stream_readable.js:453:10)
      at resume_ (_stream_readable.js:929:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
      at AsyncStream.error (/home/karl/dev/langurama/node_modules/marko/src/runtime/html/AsyncStream.js:441:13)
      at Timeout._onTimeout (/home/karl/dev/langurama/node_modules/marko/src/runtime/renderable.js:17:22)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)`

**Comment by basickarl** [comment]
Ok after removing and installing different versions of marko I've found out that the last working version is 4.5.6, this bug/issue was introduced in 4.6.0 somewhere.

**Comment by basickarl** [comment]
Ok I was able to pinpoint he commit responsible: https://github.com/marko-js/marko/commit/c962b6d9ace64b043165b7d1f8b48ebf73b6fe96
