### ISSUE TITLE
await is broken

### ISSUE THREAD

**Issue by japrescott** [marko-js/marko#1393]
### Details

I used to use the async/await feature in the past but since 4.18 has new syntax, I tried to migrate to the new syntax and it throws an error. Even with a very basic test case;

template;
```
	body
		h1 -- broken2 ${Date.now()}
		div
			await(data.async) client-reorder
				@placeholder
					div -- Displayed while promise is pending --> Loading...
				@then|person|
					div -- Hello ${person.name}!
				@catch|err|
					div -- Displayed if promise rejects --> Caught error: ${err.name}
```
templateData;
```
var data = {
	async: function() {
		return new Promise((resolve, reject) => {
			setTimeout(function() {
				resolve({
					name: "Frank"
				});
			}, 5000);
		});
	}
}
```
### Expected Behavior

I expect the template to render asynchronously first showing the h1 and then later the data

### Actual Behavior

error is thrown
```
"TypeError: Cannot read property '_L_' of undefined" `"TypeError: Cannot read property '_L_' of undefined\\n" +\n` +
  "  '    at addComponentsFromContext (/app/node_modules/marko/dist/runtime/components/index.js:19:44)\\n' +\n" +
  "  '    at getRenderedComponents (/app/node_modules/marko/dist/runtime/components/index.js:139:5)\\n' +\n" +
  "  '    at writeInitComponentsCode (/app/node_modules/marko/dist/runtime/components/index.js:147:30)\\n' +\n" +
  "  '    at ServerResponse.handleAwaitFinish (/app/node_modules/marko/dist/core-tags/components/init-components-tag.js:9:5)\\n' +\n" +
  "  '    at ServerResponse.emit (events.js:203:13)\\n' +\n" +
  "  '    at ServerResponse.EventEmitter.emit (domain.js:494:23)\\n' +\n" +
  "  '    at AsyncStream.emit (/app/node_modules/marko/dist/runtime/html/AsyncStream.js:385:24)\\n' +\n" +
  "  '    at EventEmitter.<anonymous> (/app/node_modules/marko/dist/core-tags/core/await/reorderer-renderer.js:52:21)\\n' +\n" +
  "  '    at invokeListener (/app/node_modules/events-light/src/index.js:21:22)\\n' +\n" +
  "  '    at EventEmitter.emit (/app/node_modules/events-light/src/index.js:90:13)\\n' +\n" +
  "  '    at AsyncStream._doFinish (/app/node_modules/marko/dist/runtime/html/AsyncStream.js:215:26)\\n' +\n" +
  "  '    at AsyncStream.end (/app/node_modules/marko/dist/runtime/html/AsyncStream.js:255:22)\\n' +\n" +
  "  '    at renderBody (/app/node_modules/marko/dist/core-tags/core/await/renderer.js:186:22)\\n' +\n" +
  "  '    at notifyCallbacks (/app/node_modules/marko/dist/core-tags/core/await/AsyncValue.js:37:13)\\n' +\n" +
  "  '    at AsyncValue.x_ (/app/node_modules/marko/dist/core-tags/core/await/AsyncValue.js:112:13)\\n' +\n" +
  "  '    at processTicksAndRejections (internal/process/task_queues.js:75:11)'" 'nofilename' 'nolineNumber'
```

### Your Environment

node v12.7.0

### Steps to Reproduce

see above

### Stack Trace

see above

</details>

**Comment by DylanPiercey** [comment]
This issue does not appear to be related to the code you pasted above (running that looks to be fine). It may be an issue somewhere else in your app.

Is it possible for you to share a reduced reproduction?

**Comment by japrescott** [comment]
Thank you for your reply!
I tried to isolate it and figured out that locally it works but not on my server. I removed the node_modules and reinstalled everything. Now it "magically" works! Sadly I cant provide any further information for why it exactly was not working/now is working
