### ISSUE TITLE
Perplexing error with empty dynamic text placeholders

### ISSUE THREAD

**Issue by tigt** [marko-js/marko#1403]
### Details

```marko
<p>${}</p>
```

### Expected Behavior

* Either it would output the empty string: `<p></p>`
* Or a more intelligible error than…

### Actual Behavior

```
 ERROR in ./src/pages/Search.marko
    Module build failed (from ./node_modules/@marko/webpack/loader.js):
    Error: 
    Unexpected end of input: 
                               ^
        at parseRawJavaScriptAst (/Users/kon9801/git/kwicc/node_modules/marko/src/compiler/util/parseRawJavaScriptAst.js:43:28)
        at parseExpression (/Users/kon9801/git/kwicc/node_modules/marko/src/compiler/util/parseJavaScript.js:10:32)
        at module.exports (/Users/kon9801/git/kwicc/node_modules/marko/src/compiler/util/parseExpression.js:4:12)
        at Builder.parseExpression (/Users/kon9801/git/kwicc/node_modules/marko/src/compiler/Builder.js:456:22)
        at Parser.handleBodyTextPlaceholder (/Users/kon9801/git/kwicc/node_modules/marko/src/compiler/Parser.js:365:40)
        at Parser.onPlaceholder (/Users/kon9801/git/kwicc/node_modules/marko/src/compiler/HtmlJsParser.js:18:34)
        at notifyPlaceholder (/Users/kon9801/git/kwicc/node_modules/htmljs-parser/notify-util.js:279:27)
        at endPlaceholder (/Users/kon9801/git/kwicc/node_modules/htmljs-parser/Parser.js:874:37)
        at Object.expression (/Users/kon9801/git/kwicc/node_modules/htmljs-parser/Parser.js:2652:17)
        at endExpression (/Users/kon9801/git/kwicc/node_modules/htmljs-parser/Parser.js:597:36)
        at Parser.char (/Users/kon9801/git/kwicc/node_modules/htmljs-parser/Parser.js:2303:29)
        at Parser.parse (/Users/kon9801/git/kwicc/node_modules/htmljs-parser/BaseParser.js:175:24)
        at Parser.parse (/Users/kon9801/git/kwicc/node_modules/htmljs-parser/Parser.js:3207:15)
        at HtmlJsParser.parse (/Users/kon9801/git/kwicc/node_modules/marko/src/compiler/HtmlJsParser.js:109:16)
        at Parser.parse (/Users/kon9801/git/kwicc/node_modules/marko/src/compiler/Parser.js:109:25)
        at Compiler.compile (/Users/kon9801/git/kwicc/node_modules/marko/src/compiler/Compiler.js:158:31)
        at _compile (/Users/kon9801/git/kwicc/node_modules/marko/src/compiler/index.js:91:35)
        at Object.compile (/Users/kon9801/git/kwicc/node_modules/marko/src/compiler/index.js:117:12)
        at Object.default_1 (/Users/kon9801/git/kwicc/node_modules/@marko/webpack/dist/loader/index.js:96:30)
     @ ./src/pages/Search.marko?assets 12:15-40
     @ ./src/routes.js
     @ ./src/index.js
```

### Steps to Reproduce

1.  Put `<p>${}</p>` somewhere in the marko sample Webpack repo
2. Build
3. Voila

**Comment by DylanPiercey** [comment]
With the new code-frame errors in Marko 5, I think this is now a lot better. 
![image](https://user-images.githubusercontent.com/4985201/108278421-3ff41480-7138-11eb-8063-f7375a7f5d4f.png)
