### ISSUE TITLE
Documentation Error: BodyContent

### ISSUE THREAD

**Issue by BRubinson** [marko-js/marko#1414]
### Details

The Documentation for Body content->repeated attribute tags appears to be outdated

```
{
    "@data": "array",
    "<column>": {
        "is-repeated": true
    }
}
```
is listed but causes compile-time errors

I was trying to use repeated tags to populate a dropdown component with items 

```
    Dropdown -- Click me
        @Item
            -- One
        @Item
            -- Two
        @Item
            -- Three
```

with the Marko-tag.json as

```
{
    "@data": "array",
    "<Item>": {
        "is-repeated": true
    }
}
```
### Expected Behavior

The expected behavior is for the input.column/input.Item to be an array of the column/item tags.

### Actual Behavior

Compile time error: is-repeated is not a recognized attribute of column/Item

### Possible Fix

I was looking at the app-tab in ui-component playground and found this

```
{
   "@Items <Item>[]":{
       "@label":"string"
   } 
}
```
which works as expected by population input.Items with all Item tags

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4): node
- Operating System and version (desktop or mobile): Desktop
- Link to your project:

### Steps to Reproduce

1.  Create a new component
2. Copy paste the marko.json for repeated attributes
3. try to compile
4.

### Stack Trace

```
Error: Unable to load tag ([/Users/bryce/Desktop/marko-lemon/src/components → /Users/bryce/Desktop/marko-lemon/src/components/Dropdown/marko-tag.json]): Error: Error while applying option of "<Item>". Cause: Error: Unsupported properties of [is-repeated]
    at TagLoader.* (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/loadTagFromProps.js:246:23)
    at invokeHandlers (/Users/bryce/Desktop/marko-lemon/node_modules/property-handlers/lib/index.js:68:33)
    at TagLoader.load (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/loadTagFromProps.js:121:9)
    at Object.loadTagFromProps (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/loadTagFromProps.js:745:19)
    at scanTagsDir (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/scanTagsDir.js:212:17)
    at Object.find (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-finder/index.js:114:21)
    at Object.buildLookup (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-lookup/index.js:27:32)
    at new CompileContext (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/CompileContext.js:128:36)
    at _compile (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/index.js:81:21)
    at Object.compile (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/index.js:117:12) ([/Users/bryce/Desktop/marko-lemon/src/components → /Users/bryce/Desktop/marko-lemon/src/components/Dropdown/marko-tag.json])
    at module.exports (/Users/bryce/Desktop/marko-lemon/node_modules/marko/node_modules/raptor-util/createError.js:7:50)
    at Object.loadTagFromProps (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/loadTagFromProps.js:747:15)
    at scanTagsDir (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/scanTagsDir.js:212:17)
    at Object.find (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-finder/index.js:114:21)
    at Object.buildLookup (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-lookup/index.js:27:32)
    at new CompileContext (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/CompileContext.js:128:36)
    at _compile (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/index.js:81:21)
    at Object.compile (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/index.js:117:12)
    at compile (/Users/bryce/Desktop/marko-lemon/node_modules/marko-starter/node_modules/marko/src/node-require/index.js:59:41)
    at Object.markoRequireExtension [as .marko] (/Users/bryce/Desktop/marko-lemon/node_modules/marko-starter/node_modules/marko/src/node-require/index.js:133:27)
Caused by: Error: Error while applying option of "<Item>". Cause: Error: Unsupported properties of [is-repeated]
    at TagLoader.* (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/loadTagFromProps.js:246:23)
    at invokeHandlers (/Users/bryce/Desktop/marko-lemon/node_modules/property-handlers/lib/index.js:68:33)
    at TagLoader.load (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/loadTagFromProps.js:121:9)
    at Object.loadTagFromProps (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/loadTagFromProps.js:745:19)
    at scanTagsDir (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/scanTagsDir.js:212:17)
    at Object.find (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-finder/index.js:114:21)
    at Object.buildLookup (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-lookup/index.js:27:32)
    at new CompileContext (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/CompileContext.js:128:36)
    at _compile (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/index.js:81:21)
    at Object.compile (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/index.js:117:12) ([/Users/bryce/Desktop/marko-lemon/src/components → /Users/bryce/Desktop/marko-lemon/src/components/Dropdown/marko-tag.json])
    at error (/Users/bryce/Desktop/marko-lemon/node_modules/property-handlers/lib/index.js:33:17)
    at invokeHandlers (/Users/bryce/Desktop/marko-lemon/node_modules/property-handlers/lib/index.js:75:17)
    at TagLoader.load (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/loadTagFromProps.js:121:9)
    at Object.loadTagFromProps (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/loadTagFromProps.js:745:19)
    at scanTagsDir (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-loader/scanTagsDir.js:212:17)
    at Object.find (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-finder/index.js:114:21)
    at Object.buildLookup (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/taglib/taglib-lookup/index.js:27:32)
    at new CompileContext (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/CompileContext.js:128:36)
    at _compile (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/index.js:81:21)
    at Object.compile (/Users/bryce/Desktop/marko-lemon/node_modules/marko/src/compiler/index.js:117:12)
App stopped unexpectedly
```

**Comment by Paradxil** [comment]
Any updates are appreciated, I'm experiencing this same issue.

**Comment by DylanPiercey** [comment]
@Paradxil this is something I've been meaning to look at but haven't had time yet. The long hand form (`"is-repeated": true`) is broken for some reason. You can use the shorthand as a work around:

```
   "@Items <Item>[]":{
       "@label":"string"
   }
```
