### ISSUE TITLE
loop status var crashed in <for each>

### ISSUE THREAD

**Issue by kristianmandrup** [marko-js/marko#143]
`for each="item in data.list; status-var=loop"` does not understand how to parse `status-var`. 
Crashes with:

```sh
  SyntaxError: missing ) after argument list
      at exports.runInThisContext (vm.js:53:16)
      at Module._compile (module.js:413:25)
      at Object.markoExtension [as .marko] (/Users/kristianmandrup/repos/markoa/markoa/node_modules/marko/node-require.js:79:16)
```

I can see why it fails. Needs to be fixed and have its own spec ;)

```js
    forEach(data.list; status-var=loop, function(item) {
      __tag(out,
        ___ui_button_renderer_js,
        item);
```

Should rather generate something like this:

`forEach(data.list; function(item, index) {`

After looking into `raptor-util` I think I get it. It simply uses `Array.prototype.forEach` to iterate...

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

```sh
callback - Function to execute for each element, taking three arguments:
currentValue - The current element being processed in the array.
index - The index of the current element being processed in the array.
array - The array that forEach is being applied to.
```

So the generator should just generate a callback function with all those arguments

`forEach(data.list; function(item, index, array) {`

**Comment by kristianmandrup** [comment]
I think the problem is here: `core-tag-transformer.js`

```js
    [
        'for-each', function(attr, node) {
            this['for'](attr, node);
        }
    ],
    [
        'for', function(attr, node) {
            var forEachProps = this.compiler.parseAttribute(attr, {
                    each: { type: 'custom' },
                    separator: { type: 'expression' },
                    'iterator': { type: 'expression' },
                    'status-var': { type: 'identifier' },
                    'for-loop': {
                        type: 'boolean',
                        allowExpressions: false
                    }
```

And in `ForNode.js` at `doGenerateCode`

```js
ForNode.prototype = {
    doGenerateCode: function (template) {
...
        var statusVar = this.getProperty('statusVar') || this.getProperty('varStatus');
...
        if (separator && !statusVar) {
            statusVar = '__loop';
        }
...
else if (statusVar) {
            forEachParams = [
                varName,
                statusVar
            ];

            template.statement(funcName + '(' + items + ', function(' + forEachParams.join(',') + ') {').indent(function () {
                this.generateCodeForChildren(template);
                if (separator) {
                    template.statement('if (!' + statusVar + '.isLast()) {').indent(function () {
                        template.write(template.isExpression(separator) ? separator.getExpression() : stringify(separator));
                    }, this).line('}');
                }
            }, this).line('});');
```

**Comment by kristianmandrup** [comment]
Yup, it works like this:

`<for each="item in data.list" status-var="loop">`

Not clear from docs :P

**Comment by kristianmandrup** [comment]
Damn, I see it now as the last example in the loop docs. Would be nice if it was somehow more clear.
Tidy/restructure the docs a little ;) Thanks!

```js
<for each="item in ['a', 'b', 'c']" iterator="data.reverseIterator" status-var="status">
    ${status.index}$item
</for>
```
