### ISSUE TITLE
runnning marko create hello-world produces marko produces primordials error

### ISSUE THREAD

**Issue by cekvenich** [marko-js/marko#1506]
On node v12 due to older version of graceful-fs. Please update graceful-fs version.

$ marko create hello-world
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/home/vic/.nvm/versions/node/v12.16.1/lib/node_modules/marko-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/vic/.nvm/versions/node/v12.16.1/lib/node_modules/marko-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/vic/.nvm/versions/node/v12.16.1/lib/node_modules/marko-cli/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
[vic@localhost DELETE]$ node -v
v12.16.1

**Comment by parkerproject** [comment]
You are using node `v12`, downgrade to `v10` and that should work
