### ISSUE TITLE
Cannot use components from node_modules

### ISSUE THREAD

**Issue by asieverding** [marko-js/marko#1516]
Hey, I have wrote a component in my components directory and it is working well. When I put this component into an external npm module and install it into my projekt with `npm i ..\my-component-module` it is not working anymore.

I have tried a variation between an `index.marko` file with my whole component code and only the html in my `index.marko` and the javascript in `component.js`. I have also tried to use commonjs instead of ES2015 / ES6 in my `component.js` file but none of these approaches have relove the error.

My app uses this boilerplate: <https://github.com/Teddy95/webapp-boilerplate>
My component is installed into this boilerplate as an npm module.

Component code:
```marko
class {
	onCreate () {
		this.state = {
			greeting: 'Hello World!'
		}
	}
}

p -- ${state.greeting}
```

Webpack configuration of the boilerplate:
```javascript
// Import required modules
const path = require('path')
const fs = require('fs')
const webpack = require('webpack')
const nodeExternals = require('webpack-node-externals')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const WebpackPreBuildPlugin = require('pre-build-webpack')
const { getUserAgentRegExp } = require('browserslist-useragent-regexp')
const config = require('./config')

// Get node environment
const { NODE_ENV } = process.env
const isDev = NODE_ENV === 'development'
const env = isDev ? 'development' : 'production'

// Define pre-build function
const preBuild = () => {
    // Build user agent regexp file for outdatedBrowser.js script
    var fileContent = 'module.exports = ' + getUserAgentRegExp({
        browsers: fs.readFileSync(path.resolve(__dirname, '.browserslistrc')).toString().replace('\r', '').split('\n').filter(Boolean).join(' and '),
        allowHigherVersions: true
    })
    var file = path.resolve(__dirname, 'dist', 'supportedBrowsers.js')

    if (!fs.existsSync(path.resolve(__dirname, 'dist'))) {
        fs.mkdirSync(path.resolve(__dirname, 'dist'))
    }

    fs.writeFile(file, fileContent, (err) => {
        if (err) {
            throw err
        }
    })
}

// Define webpack rules
const javascriptRule = {
    test: /\.(js|jsx)$/,
    exclude: /node_modules/,
    loader: 'babel-loader'
}

const markoRule = {
    test: /\.marko?$/,
    use: ['babel-loader', '@marko/webpack/loader']
}

const styleRule = {
    test: /\.(sass|scss|css)$/,
    use: isDev ? [
        'css-hot-loader',
        MiniCssExtractPlugin.loader,
        'css-loader',
        'sass-loader'
    ] : [
        MiniCssExtractPlugin.loader,
        'css-loader',
        'sass-loader'
    ]
}

const vectorRule = {
    test: /\.svg/,
    loader: 'svg-url-loader'
}

const imageRule = {
    test: /\.(jpg|jpeg|gif|png|ico)$/,
    use: [
        {
            loader: 'file-loader',
            options: {
                name: 'images/[name]-[hash:8].[ext]'
            }
        }
    ]
}

const mediaRule = {
    test: /\.(mp4|webm|ogg|mp3|wav|flac|aac|m4a)$/,
    use: [
        {
            loader: 'file-loader',
            options: {
                name: 'media/[name]-[hash:8].[ext]'
            }
        }
    ]
}

const fontRule = {
    test: /\.(woff|woff2|ttf|eot)$/,
    use: [
        {
            loader: 'file-loader',
            options: {
                name: 'webfonts/[name]-[hash:8].[ext]'
            }
        }
    ]
}

// Webpack config for browser
const client = {
    target: 'web',
    name: 'Client',
    mode: env,
    entry: {
        app: isDev ? [
            'webpack-hot-middleware/client?reload=true',
            './app/client.js'
        ] : ['./app/client.js'],
        outdatedBrowser: ['./app/scripts/outdatedBrowser.js']
    },
    output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'dist'),
        publicPath: config.path + '/assets/'
    },
    devServer: isDev ? {
        contentBase: path.join(__dirname, 'dist'),
        historyApiFallback: true,
        overlay: true,
        hot: true,
        stats: 'minimal',
    } : undefined,
    devtool: isDev ? 'source-map' : undefined,
    resolve: {
        extensions: ['.js', '.json', '.marko']
    },
    module: {
        rules: [javascriptRule, markoRule, styleRule, vectorRule, imageRule, mediaRule, fontRule]
    },
    plugins: [
        new WebpackPreBuildPlugin(() => {
            preBuild()
        }),
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery'
        }),
        new MiniCssExtractPlugin({
            filename: '[name].css'
        }),
        isDev && new webpack.HotModuleReplacementPlugin()
    ].filter(Boolean)
}

// Webpack config for server
const server = {
    name: 'Server',
    mode: env,
    target: 'node',
    node: {
        __filename: true,
        __dirname: true
    },
    externals: nodeExternals(),
    entry: {
        server: ['./app/server.js']
    },
    output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'dist'),
    },
    resolve: {
        extensions: ['.js', '.json', '.marko']
    },
    module: {
        rules: [javascriptRule, markoRule, vectorRule, imageRule]
    }
}

// Export configurations
module.exports = [
    server,
    client
]
```

Error message:
```
Error: C:\Users\ASieverding\Documents\GitHub\legoland\components\loader\index.marko:1
(function (exports, require, module, __filename, __dirname) { class {
                                                                    ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at AsyncStream.error (C:\Users\ASieverding\Documents\GitHub\webapp-boilerplate\node_modules\marko\src\runtime\html\AsyncStream.js:448:9)
    at Timeout._onTimeout (C:\Users\ASieverding\Documents\GitHub\webapp-boilerplate\node_modules\marko\src\runtime\renderable.js:17:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Emitted 'error' event at:
    at AsyncStream.emit (C:\Users\ASieverding\Documents\GitHub\webapp-boilerplate\node_modules\marko\src\runtime\html\AsyncStream.js:409:16)
    at AsyncStream.error (C:\Users\ASieverding\Documents\GitHub\webapp-boilerplate\node_modules\marko\src\runtime\html\AsyncStream.js:451:12)
    at Timeout._onTimeout (C:\Users\ASieverding\Documents\GitHub\webapp-boilerplate\node_modules\marko\src\runtime\renderable.js:17:16)
    [... lines matching original stack trace ...]
    at Timer.processTimers (timers.js:223:10)
```

I have testet the marko-router5 module in this boilerplate, it throws the "same" error. Please help me! I am searching a solution for a few weeks now & I have a question about this topic at stackoverflow (<https://stackoverflow.com/questions/59800988/compile-single-marko-component-with-webpack>)

Best,
Andre :)

**Comment by tigt** [comment]
What version of Node.js are you running?

**Comment by asieverding** [comment]
Node: 10.15.3
NPM: 6.11.3

In the marko-starter template my component is working fine as an npm dependency. I've found your issue [here](https://github.com/marko-js/webpack/issues/12) but removing the externals property throws another error message:

```
webpack:///./node_modules/marko/src/loader_sync?:4
        throw e;
        ^

Error: Cannot find module 'node_modules\marko\src\compiler'
    at webpackEmptyContext (webpack:///./node_modules/marko/src/loader_sync?:2:10)
    at Object.eval (webpack:///./node_modules/marko/src/loader/index-default.js?:7:90)
    at eval (webpack:///./node_modules/marko/src/loader/index-default.js?:195:30)
    at Object../node_modules/marko/src/loader/index-default.js (C:\Users\ASieverding\Documents\GitHub\webapp-boilerplate\dist\server.js:14710:1)
    at __webpack_require__ (C:\Users\ASieverding\Documents\GitHub\webapp-boilerplate\dist\server.js:20:30)
    at eval (webpack:///./node_modules/marko/src/loader/index.js?:6:20)
    at Object../node_modules/marko/src/loader/index.js (C:\Users\ASieverding\Documents\GitHub\webapp-boilerplate\dist\server.js:14721:1)
    at __webpack_require__ (C:\Users\ASieverding\Documents\GitHub\webapp-boilerplate\dist\server.js:20:30)
    at eval (webpack:///./node_modules/marko/src/index.js?:44:16)
    at Object../node_modules/marko/src/index.js (C:\Users\ASieverding\Documents\GitHub\webapp-boilerplate\dist\server.js:14687:1)
```

**Comment by asieverding** [comment]
Marko is installed in both, the boilerplate & the component module.

**Comment by DylanPiercey** [comment]
@asieverding this is something we want to fix with the webpack plugin, but currently when bundling for the server what you typically want is for it to skip all node_modules, but actually to include all Marko files since they need to be transpiled still.

You can use a regexp to get around this but it is a manual process of whitelisting packages for now like so:

```
externals: [/^(?!(?:my-components-package-a|my-components-package-b)\/?)[^./!]/]
```

The above regexp will exclude any `node_modules` except those whitelisted.

I will also add that typically you should not have multiple versions of Marko in your project. The reason being is that the Marko compiler closest to the template is actually the one which will be used to compile it, and templates compiled against different Marko versions are not always compatible. Instead it is best to make your packages use a `peerDependency` instead of a direct dependency if they aren't already.

**Comment by Teddy95** [comment]
*private account* :)
Okay thank you but this is not going to work because webpack should load some node modules (express, body-parser, etc.)

I have tried to whitelist this regexp in webpack-node-externals module:
```javascript
{
    externals: [nodeExternals({
        whitelist: [/^(?!(?:octicons-marko)\/?)[^./!]/]
    })]
}
```

But then I get the same not found error as above:
```
webpack:///./node_modules/marko/src/loader_sync?:4
	throw e;
	^

Error: Cannot find module 'node_modules/marko/src/compiler'
    at webpackEmptyContext (webpack:///./node_modules/marko/src/loader_sync?:2:10)
    at Object.eval (webpack:///./node_modules/marko/src/loader/index-default.js?:7:90)
    at eval (webpack:///./node_modules/marko/src/loader/index-default.js?:195:30)
    at Object../node_modules/marko/src/loader/index-default.js (/Users/andre/Documents/GitHub/webapp-boilerplate/dist/server.js:12291:1)
    at __webpack_require__ (/Users/andre/Documents/GitHub/webapp-boilerplate/dist/server.js:20:30)
    at eval (webpack:///./node_modules/marko/src/loader/index.js?:6:20)
    at Object../node_modules/marko/src/loader/index.js (/Users/andre/Documents/GitHub/webapp-boilerplate/dist/server.js:12302:1)
    at __webpack_require__ (/Users/andre/Documents/GitHub/webapp-boilerplate/dist/server.js:20:30)
    at eval (webpack:///./node_modules/marko/src/index.js?:44:16)
    at Object../node_modules/marko/src/index.js (/Users/andre/Documents/GitHub/webapp-boilerplate/dist/server.js:12268:1)
```

**Comment by DylanPiercey** [comment]
@Teddy95 are you by chance trying to load `marko/node-require` or `marko` directly in your code? How are you linking the client side bundles with the server side templates? Typically the `@marko/webpack/plugin` would do that but it doesn't look like you are using that.

**Comment by asieverding** [comment]
@DylanPiercey when I add `require('marko/node-require')` to my server.js script the import from npm works but not from locally installed modules.

Yes I haven't understand the marko webpack plugin yet. My webpack configuration bundles the server and the client separately and the client javascript is imported with a script tag in my template.marko file, which is rendered by Express on the server side.

```marko
import favicon from './assets/icons/favicon.svg'

<!doctype html>
html lang="en"
    head
        meta charset="utf-8"
        title -- ${out.global.title}
        meta name="author" content="Andre Sieverding"
        meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
        link rel="stylesheet" href=`${out.global.path}/assets/app.css` type="text/css"
        link rel="shortcut icon" href=favicon type="image/x-icon"
    body
        app
        script type="text/javascript" src=`${out.global.path}/assets/app.js` language="javascript"
        script type="text/javascript" src=`${out.global.path}/assets/outdatedBrowser.js` language="javascript"
```

**Comment by DylanPiercey** [comment]
@asieverding does it work for you to have:

```js
{
    externals: [nodeExternals({
        whitelist: ["marko"]
    })]
}
```

**Comment by Teddy95** [comment]
@DylanPiercey Yes this works, also without the `require('marko/node-require')`. Thank you! :D  
But the node modules which have components still have to be marko as a default instead of a peer dependency.

**Comment by DylanPiercey** [comment]
We've got a new recommended patter [here](https://github.com/marko-js/examples/blob/master/examples/webpack-express/webpack.config.js#L90-L94) that seems to solve these issues.
