### ISSUE TITLE
Template produces error when using dynamic attribute tags with default renderBody

### ISSUE THREAD

**Issue by agliga** [marko-js/marko#1626]
### Details

So when I have a template with attribute tags which are dynamic (loop and/or if statements) and a default render body, the template fails and producers an error

Error is `TypeError: Cannot read property 'w' of null`

### Possible Fix

If we don't use dynamic attributes then it works fine.

### Your Environment

- Link to your project: You know my project...

### Steps to Reproduce

```
class {
    onCreate() {
        this.state = {
        viewModel: [{
            label: '1'
        }, {
            label: '2'
        }, {
            label: '3'
        }]
    }
};
}
<ebay-fake-tabs>
    <for|tab| in=state.viewModel>
        <@tab href="https://www.ebay.com/">${tab.label}</@tab>
    </for>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ornare, quam at lacinia pretium, lacus urna luctus nisi, eget molestie massa tortor id lacus. Aenean ac fringilla lacus. Fusce vel dui ex. Vivamus luctus egestas nulla, non hendrerit purus luctus at. Maecenas vel diam enim. Pellentesque quam neque, porttitor tincidunt vestibulum at, dapibus sit amet tortor.
    </p>
</ebay-fake-tabs>
```

I get an error when trying to render the out. 
Here is partially compiled template
```
function render(input, out, __component, component, state) {
  var data = input;

  ebay_fake_tabs_tag(marko_mergeNestedTagsHelper({
      renderBody: function(out, $nestedTagebay_fake_tabs$0) {
        var $for$0 = 0;

        marko_forIn(state.viewModel, function(tab) {
          var $keyScope$0 = "[" + (($for$0++) + "]");

          ebay_fake_tabs_tab_nested_tag({
              href: "https://www.ebay.com/",
              renderBody: function(out) {
                out.w(marko_escapeXml(tab.label));
              }
            }, $nestedTagebay_fake_tabs$0);
        });

        out.w("<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ornare, quam at lacinia pretium, lacus urna luctus nisi, eget molestie massa tortor id lacus. Aenean ac fringilla lacus. Fusce vel dui ex. Vivamus luctus egestas nulla, non hendrerit purus luctus at. Maecenas vel diam enim. Pellentesque quam neque, porttitor tincidunt vestibulum at, dapibus sit amet tortor.</p>");
      }
    }), out, __component, "0");
}
```

### Stack Trace
```
  TypeError: Cannot read property 'w' of null
    at Object.renderBody (ebayui-core/src/components/ebay-fake-tabs/examples/01-fake/template.marko.js:52:13)
    at mergeNestedTags (ebayui-core/node_modules/marko/src/runtime/helpers/merge-nested-tags.js:8:11)
    at render (ebayui-core/src/components/ebay-fake-tabs/examples/01-fake/template.marko.js:37:22)
    at Template.renderer (ebayui-core/node_modules/marko/src/runtime/components/renderer.js:207:5)
    at hotReloadProxy (ebayui-core/node_modules/marko/src/hot-reload.js:98:25)
    at dynamicTag (ebayui-core/node_modules/marko/src/runtime/helpers/dynamic-tag.js:88:9)
    at ebayui-core/demo/template.marko.js:116:5
    at forOf (ebayui-core/node_modules/marko/src/runtime/helpers/for-of.js:20:7)
    at render (ebayui-core/demo/template.marko.js:107:3)
    at Template.renderer (ebayui-core/node_modules/marko/src/runtime/components/renderer.js:207:5)
Emitted 'error' event on ServerResponse instance at:
    at AsyncStream.emit (ebayui-core/node_modules/marko/src/runtime/html/AsyncStream.js:425:16)
    at AsyncStream.error (ebayui-core/node_modules/marko/src/runtime/html/AsyncStream.js:466:12)
    at Immediate.<anonymous> (ebayui-core/node_modules/marko/src/runtime/renderable.js:18:16)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by DylanPiercey** [comment]
Fixed in recent released.
