### ISSUE TITLE
TypeError: template.marko: attr.isMarkoAttribute is not a function

### ISSUE THREAD

**Issue by xtremespb** [marko-js/marko#1654]
### Details

After upgrading from version 4 to version 5, I'm seeing the following error in console:

```
ERROR in C:/Users/mmatveev/Documents/Git/zoia/src/modules/nav/web/admin/template.marko?dependencies
    Module build failed (from C:/Users/mmatveev/Documents/Git/zoia/node_modules/@marko/webpack/loader.js):
    TypeError: C:\Users\mmatveev\Documents\Git\zoia\src\modules\nav\web\admin\template.marko: attr.isMarkoAttribute is not a function
        at enter (C:\Users\mmatveev\Documents\Git\zoia\node_modules\marko\node_modules\@marko\translator-default\dist\tag\index.js:47:16)
        at NodePath._call (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:55:20)
        at NodePath.call (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:42:17)
        at NodePath.visit (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:92:31)
        at TraversalContext.visitQueue (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:115:16)
        at TraversalContext.visitMultiple (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:79:17)
        at TraversalContext.visit (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:141:19)
        at Function.traverse.node (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:82:17)
        at NodePath.visit (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:99:18)
        at TraversalContext.visitQueue (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:115:16)
        at TraversalContext.visitMultiple (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:79:17)
        at TraversalContext.visit (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:141:19)
        at Function.traverse.node (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:82:17)
        at traverse (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\index.js:64:12)
        at NodePath.traverse (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\index.js:142:24)
        at traverseAll (C:\Users\mmatveev\Documents\Git\zoia\node_modules\marko\node_modules\@marko\compiler\dist\babel-plugin\index.js:263:13)
        at PluginPass.pre (C:\Users\mmatveev\Documents\Git\zoia\node_modules\marko\node_modules\@marko\compiler\dist\babel-plugin\index.js:70:9)
        at transformFile (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\lib\transformation\index.js:96:27)
        at transformFile.next (<anonymous>)
        at run (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\lib\transformation\index.js:35:12)
        at run.next (<anonymous>)
        at Object.transform (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@babel\core\lib\transform.js:27:41)
        at transform.next (<anonymous>)
        at evaluateSync (C:\Users\mmatveev\Documents\Git\zoia\node_modules\gensync\index.js:251:28)
        at Object.sync (C:\Users\mmatveev\Documents\Git\zoia\node_modules\gensync\index.js:89:14)
        at Object.compileSync (C:\Users\mmatveev\Documents\Git\zoia\node_modules\marko\node_modules\@marko\compiler\dist\index.js:22:29)
        at _compile (C:\Users\mmatveev\Documents\Git\zoia\node_modules\marko\src\compiler\index.js:61:34)
        at compile (C:\Users\mmatveev\Documents\Git\zoia\node_modules\marko\src\compiler\index.js:74:10)
        at Object.compileForBrowser (C:\Users\mmatveev\Documents\Git\zoia\node_modules\marko\src\compiler\index.js:92:10)
        at C:\Users\mmatveev\Documents\Git\zoia\node_modules\@marko\webpack\dist\loader\index.js:106:98
        at getAndCache (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@marko\webpack\dist\loader\index.js:235:39)
        at Object.default_1 (C:\Users\mmatveev\Documents\Git\zoia\node_modules\@marko\webpack\dist\loader\index.js:106:32)
     @ C:/Users/mmatveev/Documents/Git/zoia/src/modules/nav/web/admin/template.marko?hydrate 1:0-39
```

### Expected Behavior

No errors. 

It doesn't show any warnings or error when on version 4.

### Actual Behavior

Error.

### Possible Fix

Not sure.

### Your Environment

Windows 10 64 bit / Node 14.3.0

### Steps to Reproduce

Building with Webpack.

**Comment by DylanPiercey** [comment]
@xtremespb could you check if manually adding `@marko/compiler` as a dev dependency to your app fixes the issue? (You may need to clear your lock file as well)

**Comment by xtremespb** [comment]
Unfortunately, this didn't work. Error is the same ("attr.isMarkoAttribute is not a function")

Steps to reproduce:

1. `git clone https://github.com/xtremespb/zoia.git`
2. Remove package-lock.json
3. npm i
4. `npm install marko@^5`
5. `npm i npm i @marko/compiler --save-dev`
6. `npm run config`
7. `npm run build-dev`

**Comment by DylanPiercey** [comment]
@xtremespb there is an issue right now in some cases depending on how npm decides to hoist `@babel/types`. We need to look into that and find a fix.

In the interim, it seems to work in your app if you do the following:

```
git clone https://github.com/xtremespb/zoia.git
npm i marko@^5
npm i @marko/compiler@^5 -D
rm -rf ./node_modules ./package-lock.json
npm i
npm run config
npm run build-dev
```

If that does not work please let me know, seems to work on my machine though.
Either way we'll keep this issue open because we need a better solve for it.

**Comment by xtremespb** [comment]
Seems that the sequence specified by you did the trick. Now it works.
Thank you!
