### ISSUE TITLE
Errors after Webpack 5 Migration

### ISSUE THREAD

**Issue by xtremespb** [marko-js/marko#1665]
### Marko Version: 5.1.18

Using the latest Marko 5 available.

### Details

Just migrated to Webpack 5 and trying to solve the problems. There are still some errors which are preventing me from using Webpack 5 with Marko 5.

### Expected Behavior

No errors

### Possible Fix

Do something with `\@marko\webpack\dist\plugin\index.js`?

### Your Environment

Windows 10 x64, Node 15

### Steps to Reproduce

Playing around with my [ZOIA](https://github.com/xtremespb/zoia) Project:L

1. Did update Webpack version to 5
2. Corrected the Webpack configuration file to match all the breaking changed
3. Did run ```npm run build-dev-debug```

### Stack Trace

```
[webpack-cli] HookWebpackError: Cannot read property 'name' of undefined
    at makeWebpackError (c:\Users\mmatveev\Documents\Git\zoia\node_modules\webpack\lib\HookWebpackError.js:49:9)
    at c:\Users\mmatveev\Documents\Git\zoia\node_modules\webpack\lib\Compilation.js:2389:12
    at eval (eval at create (c:\Users\mmatveev\Documents\Git\zoia\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- inner error --
TypeError: Cannot read property 'name' of undefined
    at c:\Users\mmatveev\Documents\Git\zoia\node_modules\@marko\webpack\dist\plugin\index.js:116:65
    at Compilation.updateAsset (c:\Users\mmatveev\Documents\Git\zoia\node_modules\webpack\lib\Compilation.js:3453:24)
    at c:\Users\mmatveev\Documents\Git\zoia\node_modules\@marko\webpack\dist\plugin\index.js:95:41
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read property 'name' of undefined
    at c:\Users\mmatveev\Documents\Git\zoia\node_modules\@marko\webpack\dist\plugin\index.js:116:65
    at Compilation.updateAsset (c:\Users\mmatveev\Documents\Git\zoia\node_modules\webpack\lib\Compilation.js:3453:24)
    at c:\Users\mmatveev\Documents\Git\zoia\node_modules\@marko\webpack\dist\plugin\index.js:95:41
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by DylanPiercey** [comment]
@xtremespb for that error it seems that there would have to be no browser compilers registered.

Could you share a branch of ZOIA or other simple reproduction that I could take a look at?

**Comment by xtremespb** [comment]
@DylanPiercey thanks for a quick reply.
I will create a branch for Webpack 5 + Marko 5 and will come back soon.

**Comment by xtremespb** [comment]
So I've been playing around with this error, and here is a branch for it:
[https://github.com/xtremespb/zoia/tree/webpack5](https://github.com/xtremespb/zoia/tree/webpack5)

The problem was that I've removed Client configuration from Webpack 5, so Server plugin could not find any browser compilers and was failing.
Now I can build everything with warnings, but without any critical errors. But it seems that Webpack is building the Server part incorrectly, so I get the following output when starting ZOIA server:

```
c:\Users\mmatveev\Documents\Git\zoia\build\bin\zoia.js:30
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export */ __webpack_require__.d(__webpack_exports__, {\n/* harmony export */   \"default\": () => (__WEBPACK_DEFAULT_EXPORT__)\n/* harmony export */ });\n/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ({
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
[90m    at wrapSafe (internal/modules/cjs/loader.js:1116:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1164:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1049:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:937:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m
```

Not sure if that's something what is related to the Marko plugin. 
Highly likely this PR can be closed for now.
