### ISSUE TITLE
path.isMarkoTag is not a function

### ISSUE THREAD

**Issue by Allain55** [marko-js/marko#1685]
### Details
I have the simplest config possible and I'd render the simplest HTML on the server side.
marko/node-require is required when the app starts
homepage.marko is the simplest HTML possible I created for testing
My marko setup  worked before I updated the @babel/core version but now I get this error:

```
TypeError: /$PROJECT_PATH%/resources/themes/base/pages/homepage.marko: path.isMarkoTag is not a function
at isLoopTag (/$PROJECT_PATH%/node_modules/@marko/babel-utils/dist/tags.js:161:13)
at KeyManager.resolveKey (/$PROJECT_PATH%/node_modules/@marko/translator-default/dist/util/key-manager.js:41:35)
at Object.enter (/$PROJECT_PATH%/node_modules/@marko/translator-default/dist/tag/index.js:61:42)
at NodePath._call (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:55:20)
at NodePath.call (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:42:17)
at NodePath.visit (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:92:31)
at TraversalContext.visitQueue (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:116:16)
at TraversalContext.visitMultiple (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:80:17)
at TraversalContext.visit (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:142:19)
at Function.traverse.node (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:82:17)
at NodePath.visit (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:99:18)
at TraversalContext.visitQueue (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:116:16)
at TraversalContext.visitMultiple (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:80:17)
at TraversalContext.visit (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:142:19)
at Function.traverse.node (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:82:17)
at traverse (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:62:12)
at NodePath.traverse (/$PROJECT_PATH%/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/index.js:142:24)
at traverseAll (/$PROJECT_PATH%/node_modules/@marko/compiler/dist/babel-plugin/index.js:283:13)
at PluginPass.pre (/$PROJECT_PATH%/node_modules/@marko/compiler/dist/babel-plugin/index.js:78:9)
at transformFile (/$PROJECT_PATH%/node_modules/@babel/core/lib/transformation/index.js:96:27)
at transformFile.next (<anonymous>)
    at run (/$PROJECT_PATH%/node_modules/@babel/core/lib/transformation/index.js:35:12)
    at run.next (<anonymous>)
        at Object.transform (/$PROJECT_PATH%/node_modules/@babel/core/lib/transform.js:19:41)
        at transform.next (<anonymous>)
            at evaluateSync (/$PROJECT_PATH%/node_modules/gensync/index.js:251:28)
            at Object.sync (/$PROJECT_PATH%/node_modules/gensync/index.js:89:14)
            at compileSync (/$PROJECT_PATH%/node_modules/@marko/compiler/dist/index.js:22:29)
```

### Expected Behavior
Rendering HTML using Node should work

### Actual Behavior
Error is thrown

### Possible Fix
I think the issue is because of @babel/core v7.13.10. Issue is fixed if I install @babel/core v7.13.8 but returns if I update it again.

### Your Environment
Node 15.12.0
Ubuntu 16.04.7 LTS

### Steps to Reproduce
npm i @marko/compiler@latest marko@latest
npm i -D @babel/core@7.13.10 --save-exact
require a .marko file

Note: removing @marko/compiler won't solve the problem since marko is using it internally

**Comment by DylanPiercey** [comment]
@Allain55 does this issue persist if you manually delete the `.lock` file and reinstall your node_modules?

**Comment by Allain55** [comment]
That fixes the issue, thank you! I tried npm ci multiple times but that didn't help.

**Comment by ryansolid** [comment]
`npm ci` obeys the lock file to the letter. `npm i` might have some success but it will still obey the range so sometimes depending on some weird nested dependencies you might still have like 2 versions or weirdness going on.

Glad to hear this is resolved.
