### ISSUE TITLE
Error: Cannot find module 'marko/compiler' when using the CLI compiler

### ISSUE THREAD

**Issue by lazytyper** [marko-js/marko#1698]
#### By trying the CLI compiler

`npx @marko/compile --browser test.marko`

### I'm getting this stack trace:

```
internal/modules/cjs/loader.js:969
  throw err;
  ^
Error: Cannot find module 'marko/compiler'
Require stack:
- /home/work/.npm/_npx/565074d93fe81787/node_modules/@marko/compile/dist/index.js
- /home/work/.npm/_npx/565074d93fe81787/node_modules/@marko/compile/dist/cli.js
- /home/work/.npm/_npx/565074d93fe81787/node_modules/@marko/compile/dist/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireFromRoot (/home/work/.npm/_npx/565074d93fe81787/node_modules/@marko/compile/dist/index.js:37:49)
    at Object.exports.run (/home/work/.npm/_npx/565074d93fe81787/node_modules/@marko/compile/dist/index.js:60:25)
    at run (/home/work/.npm/_npx/565074d93fe81787/node_modules/@marko/compile/dist/cli.js:64:23)
    at Object.<anonymous> (/home/work/.npm/_npx/565074d93fe81787/node_modules/@marko/compile/dist/bin.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/work/.npm/_npx/565074d93fe81787/node_modules/@marko/compile/dist/index.js',
    '/home/work/.npm/_npx/565074d93fe81787/node_modules/@marko/compile/dist/cli.js',
    '/home/work/.npm/_npx/565074d93fe81787/node_modules/@marko/compile/dist/bin.js'
  ]
}
```
#### The command

`marko-compile --browser test.marko`

throws a similar stack trace.

**Comment by lazytyper** [comment]
I think I've found the reason: `marko/compiler` is not installable atm.

`npm install marko/compiler` wants to read from a non existing repository:

```
[..................] | idealTree: timing arborist:ctor Completed in 1ms
npm ERR! code 128
npm ERR! command failed
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/marko/compiler.git
npm ERR! ERROR: Repository not found.
```

**Comment by DylanPiercey** [comment]
`marko/compiler` is not an installable module, but a subpath under the `marko` module. You need `npm install marko`.
