### ISSUE TITLE
markoExpress is not a function

### ISSUE THREAD

**Issue by YuriyTigiev** [marko-js/marko#1753]
### Marko Version: x.x.x
^5.17.3

### Details

app.js
```
require("@marko/compiler/register");
var express = require('express');
var markoExpress = require("@marko/express");

var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var ccxt = require('ccxt')

var app = express();
app.use(markoExpress());

```

### Expected Behavior

Run the code

### Actual Behavior

Returns an error 

### Your Environment

```
cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.4 (Electric Cheetah)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.4 (Electric Cheetah)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8.4:GA"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.4"

node -v
v14.17.5
npm -v
8.1.3
```

### Steps to Reproduce

`npm start`

### Stack Trace

```
[ytigiev@screener screener.market]$ npm start 

> screenermarket@0.0.1 start
> node ./bin/www

Hello world!
/var/www/html/screener.market/screener.market/app.js:13
app.use(markoExpress());
        ^

TypeError: markoExpress is not a function
    at Object.<anonymous> (/var/www/html/screener.market/screener.market/app.js:13:9)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/www/html/screener.market/screener.market/bin/www.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
```

```
{
  "name": "test",
  "version": "0.0.1",
  "description": "TEST",
  "main": "./bin/www",
  "dependencies": {
    "@marko/express": "^1.0.0",
    "as-table": "^1.0.55",
    "ccxt": "^1.61.24",
    "cjs": "^0.0.11",
    "express": "^4.17.1",
    "marko": "^5.17.3",
    "morgan": "^1.10.0",
    "serve-favicon": "^2.5.0"
  },
  "scripts": {
    "start": "node ./bin/www",
    "inspect": "node --inspect ./bin/www",
    "devstart": "nodemon ./bin/www"
  }
}


```

**Comment by DylanPiercey** [comment]
@YuriyTigiev the issue is that `@marko/express` is now published as an es module, with commonjs shim. Essentially if you are using commonjs (`require`) you need to read `.default`, like so:

```js
const markoMiddleware = require("@marko/express").default
```

**Comment by YuriyTigiev** [comment]
It helped but now I'm getting another error. Is it also related to a module?  

/view/index.js - routes
```
var express = require('express');
var router = express.Router();
const ccxt = require('ccxt');

/* GET page. */
router.get('/', async function (req, res, next) {



    var template = require("../views/index.marko");

    console.log("Routing done all fine...");
    res.marko(template, data={
      fname: "Devanshi",
      lname: "awasthi",
      host: "Vikas",
      drinks : ["Wine", "Beer", "Champagne"]});   

});
```

```
(node:49482) UnhandledPromiseRejectionWarning: TypeError: template.render is not a function
    at ServerResponse.renderMarkoTemplate [as marko] (/var/www/html/screener.market/screener.market/node_modules/@marko/express/dist/cjs/index.js:20:10)
    at /var/www/html/screener.market/screener.market/routes/index.js:39:9
    at Layer.handle [as handle_request] (/var/www/html/screener.market/screener.market/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/screener.market/screener.market/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/html/screener.market/screener.market/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/html/screener.market/screener.market/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/html/screener.market/screener.market/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/html/screener.market/screener.market/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/html/screener.market/screener.market/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/www/html/screener.market/screener.market/node_modules/express/lib/router/index.js:174:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:49482) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by DylanPiercey** [comment]
@YuriyTigiev that is actually the same issue. Marko 5+ components are actually compiled to use esmodule and thus also have a `.default` as their main export. See this: https://markojs.com/docs/marko-5-upgrade/#:~:text=const%20template%20%3D%20require(%22.%2Ftemplate.marko%22).default%3B

**Comment by YuriyTigiev** [comment]
Do you have  simple multifile examples cjs and mjs projects  for marko 5+?

Sent via the Samsung Galaxy S8+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DylanPiercey** [comment]
@YuriyTigiev you could checkout https://github.com/marko-js/examples/tree/master/examples/webpack-express which you can setup via:

```
npm init marko -- --template webpack-express
```

**Comment by YuriyTigiev** [comment]
but without the webpack and without any additional frameworks and libraries? each new thing is each new potential issue with compatibility or security.

Sent via the Samsung Galaxy S8+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DylanPiercey** [comment]
@YuriyTigiev Marko really isn't designed to be used without some kind of bundler. We have support for webpack, rollup, vite & lasso at the moment. This is primarily because Marko automatically determines which components to bundle and send to the browser with the various bundler plugins. It is possible to use Marko w/o a bundler, but it would mean all client side functionality would not work.
