### ISSUE TITLE
"Cannot read properties of null (reading 'name')" when compiling components/templates

### ISSUE THREAD

**Issue by MiloCasagrande** [marko-js/marko#1785]
### Marko Version: 5.20.5

Output from `npm ls marko`:

```
├─┬ @marko/express@1.0.0
│ └── marko@5.20.5 deduped
├─┬ @marko/webpack@9.2.2
│ └── marko@5.20.5 deduped
└─┬ marko@5.20.5
  └─┬ @marko/translator-default@5.20.5
    └── marko@5.20.5 deduped
```

### Details

When running `webpack build` to compile templates (and to serve content in a webpack based dev environment), I get the following error:

```
  ERROR in ./src/components/component/index.marko
  Module build failed (from ./node_modules/@marko/webpack/dist/loader/index.js):
  TypeError: src/components/component/index.marko: Cannot read properties of null (reading 'name')
      at NodePath._getKey (node_modules/@babel/traverse/lib/path/family.js:296:25)
      at NodePath.get (node_modules/@babel/traverse/lib/path/family.js:288:17)
      at evaluateAttr (node_modules/@marko/translator-default/dist/tag/util.js:159:21)
      at tagArguments (node_modules/@marko/translator-default/dist/tag/native-tag[vdom]/index.js:47:60)
      at _default (node_modules/@marko/translator-default/dist/tag/native-tag[vdom]/index.js:174:21)
      at _default (node_modules/@marko/translator-default/dist/tag/native-tag.js:24:32)
      at Object.exit (node_modules/@marko/translator-default/dist/tag/index.js:123:37)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:109:8)
```

When building in `production` mode, client side output is not generated, in development mode the error is thrown.

I have 140 components in total in my project, but only 3 components throw that error. Those components are included into another component (though I have other components included like that and no error is thrown by those).

### Expected Behavior

Templates are compiled without errors.
With `marko@5.20.4` it was working correctly and I didn't see any errors.

<details><summary>Additional Info</summary>

### Your Environment

- MacOS 12.3.1
- nodejs 16.14.2
- npm 8.7.0
- webpack 5.72.0
- webpack-cli 4.9.2
- webpack-dev-server 4.8.1
- webpack-node-externals 3.0.0
- spawn-server-webpack-plugin 6.2.1

</details>

**Comment by DylanPiercey** [comment]
@MiloCasagrande are you able to run

```
npm exec markoc ./src/components/component/index.marko --browser
```

And share the resulting `.marko.js` file that is output?

**Comment by MiloCasagrande** [comment]
Hi, this is the output generated:
```javascript
// Compiled using marko@5.20.5 - DO NOT EDIT
import { t as _t } from "marko/src/runtime/html/index.js";

const _marko_componentType = "src/components/factory-wave-cancel/index.marko",
      _marko_template = _t(_marko_componentType);

_marko_template.path = __filename;
export default _marko_template;
import cuid from 'cuid';
import { x as _marko_escapeXml } from "marko/src/runtime/html/helpers/escape-xml.js";
import _preserve from "marko/src/core-tags/components/preserve-tag";
import _marko_tag from "marko/src/runtime/helpers/render-tag.js";
import _marko_attr from "marko/src/runtime/html/helpers/attr.js";
import _marko_props from "marko/src/runtime/html/helpers/data-marko.js";
import _appModal from "../app-modal/index.marko";
import _marko_component from "./component.js";
import _marko_renderer from "marko/src/runtime/components/renderer.js";
const _marko_component2 = _marko_component;
_marko_template._ = _marko_renderer(function (input, out, _componentDef, _component, state) {
  const {
    wave,
    isConfirmed
  } = state;
  const formId = cuid();

  _marko_tag(_appModal, {
    "title": {
      "renderBody": out => {
        out.w("Cancel Wave &#171;");
        out.w(_marko_escapeXml(wave || ""));
        out.w("&#187;");
      }
    },
    "body": {
      "renderBody": out => {
        out.w(`<form${_marko_attr("id", _componentDef.elId(formId))} autocomplete=off accept-charset=utf-8 method=post>`);
        out.w("<p>");
        out.w("You are about to cancel the wave &#171;");
        out.w("<span class=has-text-weight-bold>");
        out.w(_marko_escapeXml(wave || ""));
        out.w("</span>");
        out.w("&#187;.");
        out.w("</p>");

        _marko_tag(_preserve, {
          "n": true,
          "renderBody": out => {
            out.w("<p class=\"mt-0 mb-0\">");
            out.w("This will stop the roll-out of this wave.");
            out.w("</p>");
          }
        }, out, _componentDef, "2");

        _marko_tag(_preserve, {
          "n": true,
          "renderBody": out => {
            out.w("<p class=mt-5>");
            out.w("In order to proceed, type ");
            out.w("<span class=\"is-uppercase has-text-weight-bold\">");
            out.w("CANCEL");
            out.w("</span>");
            out.w(" in the field below.");
            out.w("</p>");
          }
        }, out, _componentDef, "3");

        _marko_tag(_preserve, {
          "n": true,
          "renderBody": out => {
            out.w("<div class=\"field mt-1\">");
            {
              const elId = cuid();
              out.w(`<label${_marko_attr("for", _componentDef.elId(elId))} class=is-size-7>`);
              out.w("Type ");
              out.w("<span class=is-uppercase>");
              out.w("CANCEL");
              out.w("</span>");
              out.w("</label>");
              out.w("<div class=control>");
              out.w(`<input${_marko_attr("id", _componentDef.elId(elId))} class=input type=text placeholder=CANCEL name=confirm pattern=^CANCEL$ required>`);
              out.w("</div>");
            }
            out.w("</div>");
          }
        }, out, _componentDef, "5");

        out.w("</form>");
      }
    },
    "footer": {
      "renderBody": out => {
        out.w("<div class=\"buttons is-right\">");

        _marko_tag(_preserve, {
          "n": true,
          "renderBody": out => {
            out.w(`<button${_marko_props(out, _componentDef, {
              "onclick": _componentDef.d("click", "onCloseClick", false)
            })} class="button is-white is-capitalized">`);
            out.w("Close");
            out.w("</button>");
          }
        }, out, _componentDef, "10");

        out.w(`<button type=submit${_marko_attr("form", _componentDef.elId(formId))} class="button is-danger is-capitalized"${_marko_attr("disabled", !isConfirmed && true)}>`);

        _marko_tag(_preserve, {
          "n": true,
          "b": true,
          "renderBody": out => {
            out.w("Cancel");
          }
        }, out, _componentDef, "11");

        out.w("</button>");
        out.w("</div>");
      }
    }
  }, out, _componentDef, "@modal", [["modal-close", "onModalClose", false]]);
}, {
  t: _marko_componentType,
  d: true
}, _marko_component2);
_marko_template.meta = {
  id: _marko_componentType,
  component: "./index.marko",
  tags: ["../app-modal/index.marko"]
};
```

**Comment by MiloCasagrande** [comment]
I'm closing this one: I managed to solve the error/problem.

It was a mix of typo in a class attribute of an HTML element and, although I'm not sure why, giving the same key value to the same component used in two different components, and those two components are used together in another one, resulted in the error above.
