### ISSUE TITLE
Marko v3, error: Unmatched else statement 

### ISSUE THREAD

**Issue by veggiemonk** [marko-js/marko#233]
The very basic project is at https://github.com/veggiemonk/marlow-test

```
❯ node .

  Error: An error occurred while trying to compile template at path "/home/veggiemonk/code/marlow-test/src/index.marko". Error(s) in template:
  1) Unmatched else statement
  
      at Compiler.compile (/home/veggiemonk/code/marlow-test/node_modules/marko/compiler/Compiler.js:108:25)
      at Object.compileFile (/home/veggiemonk/code/marlow-test/node_modules/marko/compiler/index.js:86:25)
      at loadFile (/home/veggiemonk/code/marlow-test/node_modules/marko/runtime/loader.js:84:34)
      at load (/home/veggiemonk/code/marlow-test/node_modules/marko/runtime/loader.js:124:16)
      at Object.load (/home/veggiemonk/code/marlow-test/node_modules/marko/runtime/marko-runtime.js:295:33)
      at Object._callee2$ (server.js:22:22)
      at tryCatch (/home/veggiemonk/code/marlow-test/node_modules/babel-regenerator-runtime/runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/home/veggiemonk/code/marlow-test/node_modules/babel-regenerator-runtime/runtime.js:329:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/veggiemonk/code/marlow-test/node_modules/babel-regenerator-runtime/runtime.js:94:21)
      at onFulfilled (/home/veggiemonk/code/marlow-test/node_modules/co/index.js:65:19)


```

The basic Marko template, it was taken from one of the example: 
```html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Marko Demo</title>
</head>
<body>
<h1>Marko Demo</h1>

Hello ${data.name}!

<ul if="notEmpty(data.colors)">
    <li for="color in data.colors">
        $color
    </li>
</ul>
<div else>
    There are no colors!
</div>

</body>
</html>
```

**Comment by veggiemonk** [comment]
The template should be written like this:
```html
<ul if(notEmpty(data.colors)>
    <li for(color in data.colors)>
        $color
    </li>
</ul>
<div else>
    There are no colors!
</div>
```
Thanks @philidem for the answer on gitter.
