### ISSUE TITLE
Node 6.0.0

### ISSUE THREAD

**Issue by jsumners** [marko-js/marko#275]
It's now out as "stable," and will be the LTS release come October. So here's a fun one:

```bash
% npm test                                                                                                           

> marko@3.0.2 test /Users/jsumners/Projects/marko
> npm run init-tests && node_modules/.bin/mocha --ui bdd --reporter spec ./test && node_modules/.bin/jshint compiler/ runtime/ taglibs/


> marko@3.0.2 init-tests /Users/jsumners/Projects/marko
> ./test/init-tests.sh

/Users/jsumners/Projects/marko/node_modules/property-handlers/lib/index.js:21
                throw cause;
                ^

Error: Error while handling properties for <assign> tag in /Users/jsumners/Projects/marko/taglibs/core/marko.json: Error while applying option of "code-generator". Cause: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /Users/jsumners/Projects/marko/node_modules/raptor-modules/resolver/lib/serverResolveRequire.js:27:65
    at Object.find (/Users/jsumners/Projects/marko/node_modules/raptor-modules/resolver/lib/search-path.js:14:31)
    at serverResolveRequire (/Users/jsumners/Projects/marko/node_modules/raptor-modules/resolver/lib/serverResolveRequire.js:18:29)
    at Object.TagHandlers.codeGenerator (/Users/jsumners/Projects/marko/compiler/taglib-loader/loader-tag.js:175:20)
    at invokeHandlers (/Users/jsumners/Projects/marko/node_modules/property-handlers/lib/index.js:66:29)
npm ERR! Test failed.  See above for more details.
```

**Comment by patrick-steele-idem** [comment]
It looks like the code is being hit by the following breaking changes: https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6#path

However, we should be passing in `undefined` for the path so we should fix that. I'll take a look. Thanks for reporting the problem!

**Comment by patrick-steele-idem** [comment]
Tests for marko are passing on Node v6. Please let me know if you find any other issues. Thanks, again!
