### ISSUE TITLE
Hot Reloading doesn't work anymore, even with modification in existing templates

### ISSUE THREAD

**Issue by jainprash** [marko-js/marko#276]
@patrick-steele-idem - Note, the error is misleading, as I just modified the existing template, however the hot reloader module, somehow looks for new compiled templates.

``Error: ENOENT: no such file or directory, open '/Users/prashjain/projects/xonyx/node_modules/lasso/head-116-3-26-29630-12vpaz3.marko'
   at Error (native)
   at Object.fs.openSync (fs.js:549:18)
   at Object.fs.readFileSync (fs.js:397:15)
   at loadFile (/Users/prashjain/projects/xonyx/node_modules/marko/runtime/loader.js:82:23)
   at load (/Users/prashjain/projects/xonyx/node_modules/marko/runtime/loader.js:124:16)
   at Object.load (/Users/prashjain/projects/xonyx/node_modules/marko/runtime/marko-runtime.js:295:33)
   at Object.marko.load (/Users/prashjain/projects/xonyx/index.js:21:18)
   at Object.Template.(anonymous function) [as renderSync] (/Users/prashjain/projects/xonyx/node_modules/marko/hot-reload/index.js:67:48)
   at Object.LassoPageResult.getHtmlForSlot (/Users/prashjain/projects/xonyx/node_modules/lasso/lib/LassoPageResult.js:111:25)
   at Object.LassoPageResult.getSlotHtml (/Users/prashjain/projects/xonyx/node_modules/lasso/lib/LassoPageResult.js:150:21)
   at renderSlot (/Users/prashjain/projects/xonyx/node_modules/lasso/taglib/slot-tag.js:35:36)
   at render (/Users/prashjain/projects/xonyx/node_modules/lasso/taglib/slot-tag.js:57:9)
   at render (/Users/prashjain/projects/xonyx/node_modules/lasso/taglib/head-tag.js:9:5)
   at module.exports.t (/Users/prashjain/projects/xonyx/node_modules/marko/runtime/helpers.js:284:13)
   at render (/Users/prashjain/projects/xonyx/src/pres/layouts/ryp/desktop/ryp-layout.marko.js:44:5)
   at Object.Template.render (/Users/prashjain/projects/xonyx/node_modules/marko/runtime/marko-runtime.js:192:9)
   at Object.Template.(anonymous function) [as render] (/Users/prashjain/projects/xonyx/node_modules/marko/hot-reload/index.js:72:34)
   at render (/Users/prashjain/projects/xonyx/node_modules/marko/node_modules/marko-layout/use-tag.js:14:20)
   at module.exports.t (/Users/prashjain/projects/xonyx/node_modules/marko/runtime/helpers.js:284:13)
   at render (/Users/prashjain/projects/xonyx/src/pres/pages/ryp/desktop/ryp-page.marko.js:40:5)
   at Object.Template.render (/Users/prashjain/projects/xonyx/node_modules/marko/runtime/marko-runtime.js:192:9)
   at Object.Template.(anonymous function) [as render] (/Users/prashjain/projects/xonyx/node_modules/marko/hot-reload/index.js:72:34)
``

**Comment by patrick-steele-idem** [comment]
Hi @jainprash, I believe that had already been fixed 12 days ago: https://github.com/marko-js/marko/issues/266

What version of `marko` are you using?

**Comment by patrick-steele-idem** [comment]
I believe this issue has been resolved.
