### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by lauritzsh** [marko-js/marko#459]
### Context
I can't get `components` or custom tags working with a very simple setup. My setup is currently just `koa@next`, `koa-router@next` and `marko@3.13.0`. I have had the exact same problem with `express` so it should have nothing to do with `koa` or `express` but rather `marko`.

### Expected Behavior
Having my view display the component I am trying to render.

### Actual Behavior
I am getting `TypeError: Path must be a string. Received undefined` instead.

### Possible Fix
I have no idea, sorry.

<details><summary>Additional Info</summary>

### Your Environment
I have tried the latest version of the three latest major versions of Node.js (v5, v6 and v7). In no versions of Node it works. This is on macOS 10.12.

### Steps to Reproduce
I can setup a repository and the project if it's a requirement but it's just four very small files so I have included a [gist](https://gist.github.com/anonymous/10bd7f0445e5ae19320d531476f3ccef) instead.

To reproduce you should just run `node server.js` and go to `localhost:3000` and see an internal server error.

### Stack Trace
```
  TypeError: Path must be a string. Received undefined
      at assertPath (path.js:7:11)
      at Object.join (path.js:1213:7)
      at Object.getRootPackage (/Users/lauritz/Downloads/marko-test/node_modules/lasso-package-root/src/index.js:14:36)
      at deresolve (/Users/lauritz/Downloads/marko-test/node_modules/deresolve/src/index.js:121:48)
      at CompileContext.getRequirePath (/Users/lauritz/Downloads/marko-test/node_modules/marko/compiler/CompileContext.js:144:16)
      at CustomTag.generateCode (/Users/lauritz/Downloads/marko-test/node_modules/marko/compiler/ast/CustomTag.js:316:47)
      at Generator.generateCode (/Users/lauritz/Downloads/marko-test/node_modules/marko/compiler/CodeGenerator.js:259:44)
      at /Users/lauritz/Downloads/marko-test/node_modules/marko/compiler/CodeGenerator.js:384:22
      at ArrayContainer.forEach (/Users/lauritz/Downloads/marko-test/node_modules/marko/compiler/ast/ArrayContainer.js:18:26)
      at Generator.generateStatements (/Users/lauritz/Downloads/marko-test/node_modules/marko/compiler/CodeGenerator.js:362:15)
```

</details>

**Comment by Hesulan** [comment]
I'm not sure why, and I would definitely consider this a bug, but it seems some module along the chain (probably somewhere around `deresolve` or `lasso-package-root`) can't handle a malformed `package.json`. The one at the top of your gist gave me the same error, but running `npm init` fixed it.

**Comment by lauritzsh** [comment]
@Hesulan Nicely spotted! I played with `package.json` and adding a `name` field to the `package.json` file fixes this problem. At least I can render the component so I assume that fixes it.

I am also still considering this a bug so I will keep the issue open. At least there is a workaround/temporarily fix for this.
