### ISSUE TITLE
calling .renderSync().appendTo() with a string I appendTo() causes doc to be undefined

### ISSUE THREAD

**Issue by smulder** [marko-js/marko#493]
### Context

in dom.js exports.mixin

target[methodName] = function(referenceEl) is reached with referenceEl as a string

It then goes on to try to get the ownerDocument with referenceEl.ownerDocument which won't work on a string so doc is undefined.

it then goes through var newNode = getNode.call(this, doc); with an undefined doc but still creates the new dom element

then appendTo(newChild, referenceParentEl) is called and it appends the widget div to the referenceParentEl

it then goes into the following with the same undefined doc and emits a mount node event
if (afterInsert) {
    afterInsert.call(this, doc);
}

then emits a mount event

then entered initClientRendered(widgetDefs, doc) in init-widgets-browser.js with an undefined doc and tries to fix the undefined doc with window.doc which resolves undefined also

then initWidget(widgetDef, doc) with that undefined doc

then tries to get rootIds with var rootIds = widgetDef.roots; which returns undefined so it skips the next code block to go right to:
el = doc.getElementById(id);
el.__widget = widget;
els = [el];

this is where it errors due to doc being undefined

### Expected Behavior
getNode() should be called if the input is a string

### Actual Behavior
string is never converted to a dom reference so it continues to be treated as a string through following calls

### Possible Fix
call getNode() on initial input

### Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

### Steps to Reproduce

in a client side js file call the following (with the path changed to your widget)
1. var catProdWidget = require('src/components/cat-prod-widget');
2. catProdWidget.renderSync().appendTo('catProdList').getWidget();
3. 
4. 

### Stack Trace

Uncaught TypeError: Cannot read property 'getElementById' of undefined
    at initWidget (http://localhost:3003/static/src/marko$4.0.0-beta.4/widgets/init-widgets-browser.js:117:17)
    at Object.initClientRendered (http://localhost:3003/static/src/marko$4.0.0-beta.4/widgets/init-widgets-browser.js:238:22)
    at WidgetsContext.initWidgets (http://localhost:3003/static/src/marko$4.0.0-beta.4/widgets/WidgetsContext.js:79:21)
    at EventEmitter.<anonymous> (http://localhost:3003/static/src/marko$4.0.0-beta.4/widgets/index-browser.js:80:28)
    at EventEmitter.emit (http://localhost:3003/static/src/events$1.1.1/events.js:81:17)
    at RenderResult.afterInsert (http://localhost:3003/static/src/marko$4.0.0-beta.4/runtime/RenderResult.js:69:16)
    at RenderResult.afterInsert (http://localhost:3003/static/src/marko$4.0.0-beta.4/runtime/RenderResult.js:110:14)
    at RenderResult.exports.mixin.Object.keys.forEach.target.(anonymous function) [as appendTo] (http://localhost:3003/static/src/marko$4.0.0-beta.4/runtime/dom.js:130:29)
    at loadAll (http://localhost:3003/static/src/Tree_Fort_Bikes_5_0$1.0.0/site/public/js/tfv5.js:2722:34)
    at HTMLDocument.<anonymous> (http://localhost:3003/static/src/Tree_Fort_Bikes_5_0$1.0.0/site/public/js/tfv5.js:2620:7)
</details>

**Comment by patrick-steele-idem** [comment]
This has been resolved.
