### ISSUE TITLE
Module build failed: Error: Node does not have a `writeCode` method 

### ISSUE THREAD

**Issue by westtrade** [marko-js/marko#504]
main.marko
```
<include('../layouts/default.marko', data)>
	<@pagetitle></@pagetitle>
	<@body>
		<include ('./user.marko', data)/>
	</@body>
</include>
```
default.marko
```
<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8"/>
		<meta name="format-detection" content="telephone=no">
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, maximum-scale=1">
		<title>
			<if (data.pagetitle)><include (data.pagetitle)></include></if>
		</title>
		<link rel="stylesheet" href="/build/style/front.css">
	</head>
	<body>
		<include("../parts/sidebar.marko", data) />
		<if(data.body)>
			<main>
				<include(data.body) />
			</main>
		</if>
	</body>
</html>
```

with <!doctype html> in first line of template error has been happend
```
ERROR in ../api/views/front/layouts/default.marko
Module build failed: Error: Node does not have a `writeCode` method: {
    "type": "DocumentType"
}
    at CodeWriter.write (/var/www/node_modules/marko/compiler/CodeWriter.js:113:9)
    at writeNode (/var/www/node_modules/marko/compiler/CodeWriter.js:80:26)
    at Array.forEach (native)
    at CodeWriter.writeStatements (/var/www/node_modules/marko/compiler/CodeWriter.js:98:19)
    at CodeWriter.writeBlock (/var/www/node_modules/marko/compiler/CodeWriter.js:48:14)
    at FunctionDeclaration.writeCode (/var/www/node_modules/marko/compiler/ast/FunctionDeclaration.js:60:16)
    at CodeWriter.write (/var/www/node_modules/marko/compiler/CodeWriter.js:115:18)
    at writeNode (/var/www/node_modules/marko/compiler/CodeWriter.js:80:26)
    at Array.forEach (native)

    at CodeWriter.writeStatements (/var/www/node_modules/marko/compiler/CodeWriter.js:98:19)
    at Program.writeCode (/var/www/node_modules/marko/compiler/ast/Program.js:16:16)
    at CodeWriter.write (/var/www/node_modules/marko/compiler/CodeWriter.js:115:18)
    at CompiledTemplate.get code [as code] (/var/www/node_modules/marko/compiler/Compiler.js:99:20)
    at _compile (/var/www/node_modules/marko/compiler/index.js:90:24)
    at compile (/var/www/node_modules/marko/compiler/index.js:100:12)
    at Object.compileForBrowser (/var/www/node_modules/marko/compiler/index.js:111:12)
    at Object.module.exports (/var/www/node_modules/marko-loader/src/index.js:7:30)
 @ ../api/views/front/common/404.marko 2:23-58
```

without DOCTYPE it works.

Type of compile - vdom with compileFileForBrowser function.

**Comment by Hesulan** [comment]
I can't think of any use-cases where this would really be necessary, but I also can't see much reason to throw an error. Browsers seem to silently remove the `<!DOCTYPE>` tag whenever it occurs somewhere it shouldn't, I feel like that's probably the best thing for Marko to do as well.

**Comment by westtrade** [comment]
I just tried to reuse server templates on client side. I find another way how can i do it - with components, but... i think it will be very nice feature - if rendering for client can omit doctype tag in server template and compile only head and body. And as for me it will be very coolest if template can override styles and title of document)
