### ISSUE TITLE
[v4] Bug related to textarea

### ISSUE THREAD

**Issue by mindeavor** [marko-js/marko#511]
### Context

```js
<script>
module.exports = {
  onInput(attrs) {
    this.state = { code: '// Your code here', errorText: '' }
  },
  submit() {
    this.state.errorText = 'Placeholder error'
  }
}
</script>

<div class="code-editor">
  <h3>Code Editor</h3>
  <div><textarea>${state.code}</textarea></div>
  <button on-click('submit')>Run Code</button>
  <pre class="error-message">${state.errorText}</pre>
</div>
```

### Expected Behavior

The `<pre>` should be populated with `Placeholder error` after clicking the button.

### Actual Behavior

Clicking the button throws an error.

<details><summary>Additional Info</summary>

### Your Environment

* Version used: v4.0.0-beta.10
* Environment name and version: Chrome
* Operating System and version (desktop or mobile): OS X 10.11.6

### Steps to Reproduce
1. Load page
2. Click the button

### Stack Trace

```text
Uncaught TypeError
  at HTMLElement.$__appendChild (http://localhost:4000/static/step-2-challenge/marko$4.0.0-beta.10/runtime/vdom/Node.js:71:23)
  at HTMLElement.e (http://localhost:4000/static/step-2-challenge/marko$4.0.0-beta.10/runtime/vdom/HTMLElement.js:94:26)
  at render (http://localhost:4000/static/step-2-challenge/admissions$0.1.0/client/components/code-editor/index.marko.js:39:6)
  at renderer (http://localhost:4000/static/step-2-challenge/marko$4.0.0-beta.10/widgets/renderer.js:273:9)
  at http://localhost:4000/static/step-2-challenge/marko$4.0.0-beta.10/widgets/Widget.js:441:13
  at Object.batchUpdate [as $__batchUpdate] (http://localhost:4000/static/step-2-challenge/marko$4.0.0-beta.10/widgets/update-manager.js:89:9)
  at Widget.rerender (http://localhost:4000/static/step-2-challenge/marko$4.0.0-beta.10/widgets/Widget.js:437:23)
  at Widget.doUpdate (http://localhost:4000/static/step-2-challenge/marko$4.0.0-beta.10/widgets/Widget.js:415:14)
  at Widget.update (http://localhost:4000/static/step-2-challenge/marko$4.0.0-beta.10/widgets/Widget.js:378:18)
  at updateWidgets (http://localhost:4000/static/step-2-challenge/marko$4.0.0-beta.10/widgets/update-manager.js:70:16)
```

</details>

**Comment by patrick-steele-idem** [comment]
New version published with fix: `marko@4.0.0-beta.12`

Thanks for beta testing and reporting the problem!
