### ISSUE TITLE
[v4] Empty class tag needed for stateless component

### ISSUE THREAD

**Issue by mindeavor** [marko-js/marko#565]
## Bug Report

Feel free to close if this is intentional.

When creating a component that relies solely on `input`, an empty `class {}` is needed if one wants to bubble events.

For example:

```jsx
<!-- Without class {}, component breaks -->
class {}

<div class="custom-field">
  <input type=input.type value=input.value on-change('emit', 'change') />
</div>
```
<details><summary>Additional Info</summary>

### Your Environment

* Version used: rc.12

### Stack Trace

```
Error: An error occurred while trying to compile template at path "<clipped>/client/components/field/index.marko". Error(s) in template:
1) [client/components/field/index.marko:5:2] Unable to handle event "change". HTML element is not nested within a widget.

    at handleErrors (<clipped>/node_modules/marko/compiler/Compiler.js:82:21)
    at Compiler.compile (<clipped>/node_modules/marko/compiler/Compiler.js:147:9)
    at _compile (<clipped>/node_modules/marko/compiler/index.js:88:33)
    at Object.compile (<clipped>/node_modules/marko/compiler/index.js:102:12)
    at compile (<clipped>/node_modules/marko/node-require.js:34:37)
    at Object.markoRequireExtension [as .marko] (<clipped>/node_modules/marko/node-require.js:120:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at meta.tags.forEach.tagPath (<clipped>/node_modules/marko/runtime/dependencies/index.js:33:35)
    at Array.forEach (native)
    at getDeps (<clipped>/node_modules/marko/runtime/dependencies/index.js:31:19)
    at meta.tags.forEach.tagPath (<clipped>/node_modules/marko/runtime/dependencies/index.js:33:27)
    at Array.forEach (native)
```

</details>

**Comment by patrick-steele-idem** [comment]
This is the expected behavior. I think adding a `class {}` makes the intent clear even if it is just empty.
