### ISSUE TITLE
Unexpected strict mode reserved word error happening today [Working till yesterday]

### ISSUE THREAD

**Issue by npadhya** [marko-js/marko#592]
> This was working till yesterday

let templateSrc = fs.readFileSync(filename, {encoding: 'utf8'});
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/npadhya/Git/ParinaamSample/node_modules/marko/runtime/loader/index.js:21:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by npadhya** [comment]
Wrong node version
