### ISSUE TITLE
named single-file component doesn't work

### ISSUE THREAD

**Issue by drewfish** [marko-js/marko#606]
### Context
I'm trying to use a single-file component as `components/{name}.marko` instead of `components/{name}/index.marko`.

### Expected Behavior
App starts and is able to serve that page (localhost:8000).

### Actual Behavior
The stacktrace below is thrown when the app starts.

### Your Environment
* Version used:
  * marko 4.0.0
  * lasso 2.11.5
  * lasso-marko 2.3.0

### Steps to Reproduce
1. clone https://github.com/drewfish/marko-bug606
2. run `npm install`
3. run `node server.js` and see the error as mentioned

### Stack Trace
```
/Users/drew/dev/node-moomet/research/bugx/node_modules/marko/compiler/Compiler.js:84
        throw error;
        ^

Error: An error occurred while trying to compile template at path "/Users/drew/dev/node-moomet/research/bugx/components/page-meter/index.marko". Error(s) in template:
1) [components/page-meter/index.marko:9:13] Unrecognized tag: meter-channel - More details: https://github.com/marko-js/marko/wiki/Error:-Unrecognized-Tag

    at handleErrors (/Users/drew/dev/node-moomet/research/bugx/node_modules/marko/compiler/Compiler.js:82:21)
    at Compiler.compile (/Users/drew/dev/node-moomet/research/bugx/node_modules/marko/compiler/Compiler.js:151:9)
    at _compile (/Users/drew/dev/node-moomet/research/bugx/node_modules/marko/compiler/index.js:89:33)
    at Object.compile (/Users/drew/dev/node-moomet/research/bugx/node_modules/marko/compiler/index.js:103:12)
    at compile (/Users/drew/dev/node-moomet/research/bugx/node_modules/marko/node-require.js:52:38)
    at Object.markoRequireExtension [as .marko] (/Users/drew/dev/node-moomet/research/bugx/node_modules/marko/node-require.js:120:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by drewfish** [comment]
Hmm... it looks like I can workaround this by adding entries to my marko.json like this:
```json
{
    "<meter-channel>": {
        "renderer": "./components/meter-channel.marko"
    },
    "tags-dir": "./components"
}
```

**Comment by drewfish** [comment]
Looking at the implementation of compiler/taglib-loader/scanTagsDir.js this might be a feature request (instead of a bug) :)

**Comment by patrick-steele-idem** [comment]
For consistency we should also automatically discover custom tags that are outside a directory
