### ISSUE TITLE
Reference file breaking: renderFunc is not a function

### ISSUE THREAD

**Issue by basickarl** [marko-js/marko#641]
Hi! When I'm developing I sometimes I edit several files for something to work. Sometimes however I receive the following error:

```
  Error: Render error. Exception: TypeError: renderFunc is not a function
      at safeRender (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:6:9)
      at Template.render (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:131:20)
      at Readable._read (/home/karl/dev/instanty/node/node_modules/marko/runtime/stream.js:44:17)
      at Readable.read (_stream_readable.js:350:10)
      at resume_ (_stream_readable.js:739:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
      at AsyncStream.error (/home/karl/dev/instanty/node/node_modules/marko/runtime/html/AsyncStream.js:411:13)
      at Timeout._onTimeout (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:12:22)
      at ontimeout (timers.js:380:14)
      at tryOnTimeout (timers.js:244:5)
      at Timer.listOnTimeout (timers.js:214:5)
```

That I receive and exception is brilliant. However it would be really *really* nice if it could reference where my application is breaking. Or am I missing something?

**Comment by patrick-steele-idem** [comment]
You are right that the error message is not helpful. I've not seen that error message. Any suggestions on how to reproduce to see if we can improve the error message? Are you only able to trigger the problem when using `browser-refresh` and modifying templates?

**Comment by basickarl** [comment]
Hi! Unfortunately I can't recreate it at will I'm afraid. It however does seem to popup for me quite often. Here is a longer log:

```
[browser-refresh] Triggering refresh of client styles...
[browser-refresh] Refresh triggered
[browser-refresh] Refresh triggered
[browser-refresh] File has been changed: src/client/components/app-footer/_flags.scss
[browser-refresh] Special reload: /src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[browser-refresh] Triggering refresh of client styles...
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso] File modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[lasso/browser-refresh] StyleSheet modified: /home/karl/dev/instanty/node/src/client/components/app-footer/_flags.scss
[browser-refresh] Triggering refresh of client styles...
[browser-refresh] Refresh triggered
[browser-refresh] Refresh triggered

  Error: Render error. Exception: TypeError: renderFunc is not a function
      at safeRender (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:6:9)
      at Template.render (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:131:20)
      at Readable._read (/home/karl/dev/instanty/node/node_modules/marko/runtime/stream.js:44:17)
      at Readable.read (_stream_readable.js:350:10)
      at resume_ (_stream_readable.js:739:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
      at AsyncStream.error (/home/karl/dev/instanty/node/node_modules/marko/runtime/html/AsyncStream.js:411:13)
      at Timeout._onTimeout (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:12:22)
      at ontimeout (timers.js:380:14)
      at tryOnTimeout (timers.js:244:5)
      at Timer.listOnTimeout (timers.js:214:5)

Render error. Exception: TypeError: renderFunc is not a function
    at safeRender (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:6:9)
    at Template.render (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:131:20)
    at Readable._read (/home/karl/dev/instanty/node/node_modules/marko/runtime/stream.js:44:17)
    at Readable.read (_stream_readable.js:350:10)
    at resume_ (_stream_readable.js:739:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

  Error: Render error. Exception: TypeError: renderFunc is not a function
      at safeRender (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:6:9)
      at Template.render (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:131:20)
      at Readable._read (/home/karl/dev/instanty/node/node_modules/marko/runtime/stream.js:44:17)
      at Readable.read (_stream_readable.js:350:10)
      at resume_ (_stream_readable.js:739:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
      at AsyncStream.error (/home/karl/dev/instanty/node/node_modules/marko/runtime/html/AsyncStream.js:411:13)
      at Timeout._onTimeout (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:12:22)
      at ontimeout (timers.js:380:14)
      at tryOnTimeout (timers.js:244:5)
      at Timer.listOnTimeout (timers.js:214:5)

Render error. Exception: TypeError: renderFunc is not a function
    at safeRender (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:6:9)
    at Template.render (/home/karl/dev/instanty/node/node_modules/marko/runtime/renderable.js:131:20)
    at Readable._read (/home/karl/dev/instanty/node/node_modules/marko/runtime/stream.js:44:17)
    at Readable.read (_stream_readable.js:350:10)
    at resume_ (_stream_readable.js:739:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I'll update if I see anything new or figure out a pattern.

**Comment by DylanPiercey** [comment]
If someone could share a simplified reproduction repo that we could take a look at, we can try to see what's going on here. I'm going to close this for now, but if it is still reproducible lets create a new issue.
