### ISSUE TITLE
if statement doesn't get correctly compiled

### ISSUE THREAD

**Issue by matteozambon89** [marko-js/marko#659]
### Context
On a new component with `index.marko`, create a single `<if(state.myVar)>test</if>` and run the server.
 
### Expected Behavior
The component `index.marko.js` should contain `function render(input, out, __component, component, state) {`

### Actual Behavior
The component `index.marko.js` contains `function render(input, out) {`

### Your   ##Environment
* Version used: marko@4.2.7
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 57.0.2987.133 , node.js 7.2.1
* Operating System and version (desktop or mobile): desktop MacOS X 10.12.4 beta

### Steps to Reproduce
1. Create a component with a single line `<if(state.myVar)>test</if>`
2. Add `onCreate` to component where `this.state = input`
3. Add `onMount` to component where `this.setState('myVar', 123)`
4. Pass component to a page
5. Load the page

### Stack Trace

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Render error. Exception: ReferenceError: state is not defined
    at render (**/views/components/my-form/index.marko.js:29:7)
    at renderCompontent (**/node_modules/marko/components/taglib/helpers/renderComponent.js:3:5)
    at render (**/views/components/app/index.marko.js:21:3)
    at renderer (**/node_modules/marko/components/renderer.js:191:9)
    at render (**/views/pages/form/index.marko.js:33:3)
    at safeRender (**/node_modules/marko/runtime/renderable.js:6:9)
    at Template.render (**/node_modules/marko/runtime/renderable.js:136:20)
    at ServerResponse.response.marko (**/node_modules/marko/express.js:47:18)
    at app.get (**/server.js:74:7)
    at Layer.handle [as handle_request] (**/node_modules/router/lib/layer.js:93:5)
    at AsyncStream.error (**/node_modules/marko/runtime/html/AsyncStream.js:411:13)
    at Timeout._onTimeout (**/node_modules/marko/runtime/renderable.js:17:22)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by patrick-steele-idem** [comment]
This is related to: https://github.com/marko-js/marko/issues/589

@mlrawlings We need to work on the fix for #589

The following template is not compiled as a UI because of the surrounding `<if>`:

```marko
class {
    onCreate(input) {
        this.state = {
            foo: false
        };
    }
    onMount() {
        this.state.foo = true;
    }
}

<if(state.foo)>
    <div.foo></div>
</if>
<else>Loading...</else>
```

Keeping this issue so that we add it as a test case when we work on #589
