### ISSUE TITLE
TypeError: Cannot read property 'stack' of undefined

### ISSUE THREAD

**Issue by NikkiDreams** [marko-js/marko#719]
Hey, this is more a warning than anything else. Express 5 will be coming pretty soon-ish. I was just testing it out and ran into a little error. 
That's all. :-)

```
/.../node_modules/marko/src/express.js:16
        parent._router.stack.pop();
                      ^

TypeError: Cannot read property 'stack' of undefined
    at Function.onmount (/.../node_modules/marko/src/express.js:16:23)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:101:20)
    at Function.emit (events.js:191:7)
    at Function.<anonymous> (/.../node_modules/express/lib/application.js:234:8)
    at Array.forEach (native)
    at Function.use (/Users/nishannon/www/cash-donations/node_modules/express/lib/application.js:213:7)
    at Object.<anonymous> (/.../server.js:56:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

```
npm version
{ npm: '5.0.0',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.7.2',
  openssl: '1.0.2k',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.11.0',
  v8: '5.5.372.41',
  zlib: '1.2.11' }
```

```
"dependencies": {
    "SassMagic": "W3cplus/SassMagic",
    "app-module-path": "^2.2.0",
    "babel-cli": "^6.24.1",
    "babel-core": "^6.23.1",
    "babel-eslint": "^7.2.3",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-module-resolver": "^2.7.1",
    "babel-plugin-syntax-async-functions": "^6.13.0",
    "babel-plugin-transform-async-to-generator": "^6.22.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-regenerator": "^6.22.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-latest": "^6.24.1",
    "babel-preset-modern-browsers": "^9.0.2",
    "babel-register": "^6.23.0",
    "babel-runtime": "^6.23.0",
    "bluebird": "^3.4.7",
    "body-parser": "^1.17.2",
    "browser-refresh": "^1.7.1",
    "browser-refresh-taglib": "^1.1.0",
    "chai": "^3.5.0",
    "compression": "^1.6.2",
    "crypto": "^0.0.3",
    "debug": "^2.6.8",
    "eslint": "^3.19.0",
    "eslint-config-marko": "^1.0.1",
    "eslint-config-marko-tester": "^1.2.0",
    "eslint-import-resolver-babel-module": "^3.0.0",
    "eslint-plugin-babel": "^4.1.1",
    "eslint-plugin-flowtype": "^2.32.1",
    "eslint-plugin-json": "^1.2.0",
    "eslint-plugin-mocha": "^4.9.0",
    "eslint-plugin-prettier": "^2.1.1",
    "express": "5.0.0-alpha.2",
    "fs": "^0.0.1-security",
    "helmet": "^3.6.1",
    "hoek": "^4",
    "immutability-helper": "^2.2.0",
    "jquery": "^3.2.1",
    "lasso": "^2.11.11",
    "lasso-autoprefixer": "^2.0.0",
    "lasso-babel-transform": "^1.0.1",
    "lasso-less": "^2.4.3",
    "lasso-marko": "^2.3.0",
    "lasso-sass": "^2.0.0",
    "lasso-tools": "^2.0.9",
    "lodash": "/sunghcho/lodash.git#c0bc44d70d863418fa85a5f8594f502e85a3d8bc",
    "logging-inc": "^4.0.0",
    "marko": "4.4.6",
    "marko-devtools": "git://github.com/marko-js/marko-devtools#v1.0.6",
    "marko-tester": "^6.26.0",
    "minimatch": "^3.0.4",
    "mocha": "^3.4.1",
    "modify-babel-preset": "^3.2.1",
    "moment": "^2.18.1",
    "node-sass": "^4.5.2",
    "prettier": "^1.3.1",
    "request-debug": "^0.2.0",
    "request-promise": "^4.2.1",
    "request-promise-native": "^1.0.4",
    "serve-static": "^1.12.3",
    "skin-ebay": "^2.9.0",
    "tls": "^0.0.1",
    "uuid": "^3.0.1"
  }
}
```

**Comment by patrick-steele-idem** [comment]
Thanks for opening the issue @NikkiDreams!

@mlrawlings can you please take a look at this and see what we need to do to be compatible with Express 5? Thanks!

**Comment by austinkelleher** [comment]
I think I have a fix for this @patrick-steele-idem

**Comment by patrick-steele-idem** [comment]
Sounds good @austinkelleher. Yours now :)
