### ISSUE TITLE
How can I save the page on disk when rendering?

### ISSUE THREAD

**Issue by loopArray** [marko-js/marko#724]
When I use the Marko server as the rendering of the page, I want to put some pages saved to disk, with the configuration of the nginx that the next visit to visit a static page, but now I like to do, what should I do?
```
var writeStream = fs.createWriteStream('static/output.html');
...
...

res.marko(template, {
    name: 'Frank',
    count: 30,
    colors: ['red', 'green', 'blue']
}).pipe(writeStream);
```
That's also not OK
```
var stream = template.stream({
    name: 'Frank',
    count: 30
});

stream.pipe(res).pipe(writeStream);
```

**Comment by mlrawlings** [comment]
I believe you want:

```js
var writeStream = fs.createWriteStream(outputPath);
var stream = template.stream(inputData);

res.set('content-type', 'text/html');
stream.pipe(res);
stream.pipe(writeStream);
```

**Comment by loopArray** [comment]
Thank‘s for you replay.
It' work fist ok, then refresh made a mistake.
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:193:12)
    at WriteStream.Writable.write (_stream_writable.js:244:5)
    at Readable.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:101:20)
    at Readable.emit (events.js:188:7)
    at Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by loopArray** [comment]
I'am so sorry.
I made a terrible mistake, I have declared route outside of writeStream.It was careless of me.
Thank you very much for the solution you provided.
