### ISSUE TITLE
Error when using `static` keyword and `lasso-resource` tag in the same file

### ISSUE THREAD

**Issue by tellnes** [marko-js/marko#926]
### Marko Version: 4.5.6

$ ./node_modules/.bin/markoc --version
markoc@4.5.6
marko@4.5.6

### Expected Behavior

Compilation success.

### Actual Behavior

Errors.

<details><summary>Additional Info</summary>

### Your Environment

```
$ node -v
v8.9.1
```

### Steps to Reproduce

1. Create a file with the following contents:
```
static console.log('Hello World')
lasso-resource path="./favicon.ico" var="favicon"
```
2. Run `./node_modules/.bin/markoc test.marko`

### Stack Trace

```
Compiling:
  Input:  test.marko
  Output: test.marko.js

The following errors occurred:
- Failed to compile "test.marko". Error: Error: An error occurred while trying to compile template at path "/test.marko". Error(s) in template:
1) [test.marko:1:0] static is a static tag and can only be declared at the template root

    at handleErrors (/node_modules/marko/src/compiler/Compiler.js:82:21)
    at Compiler.compile (/node_modules/marko/src/compiler/Compiler.js:164:9)
    at _compile (/node_modules/marko/src/compiler/index.js:92:33)
    at /node_modules/marko/src/compiler/index.js:147:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```
</details>

**Comment by DylanPiercey** [comment]
Fixed in #959
